NethServer/nethsecurity

- config/luci.conf
The package should not belong to the basic image
> packages: remove openwisp

- packages/ns-plug/files/ns-plug
To test it:
```
uci delete rpcd.controller; sh -x /usr/sbin/ns-plug
```
See also NethServer/nextsecurity-controller#2
> ns-plug: handle waiting list

- packages/ns-migration/Makefile
- packages/ns-migration/files/ns-import
- packages/ns-migration/files/scripts/dhcp
Import:
- DHCP ranges
- DHCP static leases (reservations)
- Number of max leases
See also https://github.com/NethServer/nethserver-firewall-migration/pull/1
> DHCP migration

- LICENSE
- README.md
- builder/build-builder
- builder/entrypoint.sh
- builder/make.sh
- packages/ns-plug/Makefile
- packages/ns-plug/files/ns-plug
- packages/ns-plug/files/ns-plug.init
- packages/ns-ui/Makefile
- run
- Add license best practice
- Add missing license headers
- Switch to GPLv2 as upstream project
> Fix license

- README.md
- builder/build-builder
- builder/entrypoint.sh
- patches/feeds/packages/100-adblock-bypass.patch
> Builder package patches

- config/python3-nextsec.conf
- packages/python3-nextsec/Makefile
- packages/python3-nextsec/README.md
See the source repo: https://github.com/NethServer/python3-nextsec
This is required for #30
> packages: add python3-nextsec library

- config/ns-openvpn.conf
- packages/ns-openvpn/Makefile
- packages/ns-openvpn/README.md
- packages/ns-openvpn/files/01-check-status
- packages/ns-openvpn/files/10-static-lease
- packages/ns-openvpn/files/80-save-connection
- packages/ns-openvpn/files/80-save-disconnection
- packages/ns-openvpn/files/init-connections-db
- packages/ns-openvpn/files/ns-openvpnrw-add
- packages/ns-openvpn/files/ns-openvpnrw-init-pki
- packages/ns-openvpn/files/ns-openvpnrw-print-client
- packages/ns-openvpn/files/ns-openvpnrw-revoke
- packages/ns-openvpn/files/ns-openvpnrw-setup
- packages/ns-openvpn/files/openvpn-connect
- packages/ns-openvpn/files/openvpn-disconnect
Implement Nextsecurity OpenVPN extensions
This is required for #25
> ns-openvpn: add NS OpenVPN service

- docs/pppoe.md
- packages/ns-migration/files/scripts/network
- packages/ns-migration/files/scripts/nsmigration.py
Import PPPoE configuration from NS7
> Import PPPoE

- packages/ns-migration/files/scripts/network
https://trello.com/c/kaBRn0ES/38-network-migration-bridges-and-bonds
> ns-migration: handle vlan, aliases and bonds

- packages/ns-migration/README.md
- packages/ns-migration/files/ns-import
- packages/ns-migration/files/scripts/dhcp
- packages/ns-migration/files/scripts/ipsec
- packages/ns-migration/files/scripts/network
- packages/ns-migration/files/scripts/routes
- packages/ns-migration/files/scripts/wan
- packages/python3-nextsec/Makefile
Move some functions inside utilities package
> Refactor python nextsec

- files/etc/uci-defaults/99-nextsec-console_login
https://trello.com/c/eyzLONyp/17-console-login
> Enable login on console

- config/timezone.conf
- packages/ns-flashstart/files/flashstart-apply
- packages/ns-migration/Makefile
- packages/ns-migration/files/ns-import
- packages/ns-migration/files/scripts/network
- packages/ns-migration/files/scripts/time
- packages/ns-migration/files/zonename2timezone
Make sure all zones are ready before activating the firewall rules.
> ns-migration: reorder import scripts

- builder/build-builder
- builder/make.sh
- files/usr/sbin/install-nx.sh
Added compressed ext4 image to itself (in a VFAT partition) 
Included install-nx.sh script to final image with support for multiple firmwares
> NextSecurity: Allow the installation directly from the USB stick

- packages/ns-migration/files/scripts/rules
fw4 will automatically disable invalid rules
> ns-migration: do not disable rules

- config/debugtools.conf
- config/usb.conf
Add more debug tools:
- lsusb with usbids
- screen
- full ping command
- arpping command
> Add more utils

- config/debugtools.conf
dig is usefull to debug DNS problems
> conf: add dig utility

- patches/feeds/packages/100-adblock-disable.patch
Prevent conflicts con DNS on first startup
> adblock: disable service by default

- packages/ns-migration/README.md
- packages/ns-migration/files/ns-import
- packages/ns-threat_shield/Makefile
- packages/ns-threat_shield/README.md
- packages/ns-threat_shield/files/20_threat_shield
- packages/ns-threat_shield/files/ts-dns
Drop ts_dns init script and merge to adblock.
TODO:
> Refactor tsdns

- files/etc/uci-defaults/90-nextsec-root-password
Avoid to overwrite the existing password on upgrade
> uci-defaults: fix root password

- config/ns-api.conf
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/api-cli
- packages/ns-api/files/ns.talkers
- packages/ns-api/files/ns.talkers.json
- Add new ns-api package
- Expose first API: `ns.talkers`, list hosts which are generating most network traffic
> packages: add ns-api

- packages/ns-migration/files/scripts/subscription
- packages/ns-plug/Makefile
- packages/ns-plug/README.md
- packages/ns-plug/files/20_ns-plug
- packages/ns-plug/files/inventory
- packages/ns-plug/files/register
- packages/ns-plug/files/send-heartbeat
- packages/ns-plug/files/send-inventory
- packages/ns-plug/files/unregister
Add my.nethesis.it/my.nethserver.com integration:
- register the machine
- unregister the machine
- send heartbeat
- send inventory
Note:
- my.nethserver.com: all server details are shown
- my.nethesis.it: server details are not shown because the server needs some UI updates
TODO:
> ns-plug: add inventory, register, heartbeat

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/api-cli
- packages/ns-api/files/ns.ovpntunnel
- packages/ns-api/files/ns.ovpntunnel.json
- packages/ns-openvpn/files/ns-openvpntunnel-add-client
Basic API to:
- import/export OpenVPN tunnels using NS 7 JSON format
- add OpenVPN tunnel server
> ns-api: add ns.ovpntunnel

- packages/ns-don/Makefile
- packages/ns-don/files/don
Restrict remote access only to don ssh server instance.
This PR also doesn't write anything on the disk.
> ns-don: replace dropbear with openssh-server

- packages/ns-plug/files/ns-plug
Depends on: NethServer/nextsecurity-controller#5
> Rsyslog Promtail configuration

- packages/ns-plug/files/ns-plug
Moved rsyslog configuration before starting the VPN, due to exec blocking the setup.
Forgot to add uci commit at the end.
> Fixed ns-plug rsyslog

- packages/ns-plug/README.md
- packages/ns-plug/files/send-backup
Avoid to create the backup every night
> Exclude acme temporary file form backup

- packages/adblock/files/adblock.init
- packages/ns-plug/Makefile
- packages/ns-plug/README.md
- packages/ns-plug/files/register
- packages/ns-plug/files/unregister
- packages/ns-threat_shield/Makefile
- packages/ns-threat_shield/README.md
- packages/ns-threat_shield/files/ts-dns.hook
- packages/ns-threat_shield/files/ts-ip.register
- packages/ns-threat_shield/files/ts-ip.unregister
See https://trello.com/c/t5LJVP0w/88-subscription-event
> ns-plug: add register/unregister hooks

- packages/ns-api-server/Makefile
- packages/ns-api-server/files/ns-api-server.initd
Wait for https://github.com/NethServer/ns-api-server/pull/1
> Integrate API server

- builder/build-builder
- builder/entrypoint.sh
- docs/build.md
- docs/license_headers.md
- docs/quickstart.md
Allow to change or remove non-compatible pages.
> builder: switch to LuCI NethServer fork

- packages/ns-ui/Makefile
Remove old UI and import the new one.
> ns-ui: import new UI

- packages/ns-api-server/Makefile
Increase ns-api-server version to 0.0.3
> ns-api-server. update version

- files/usr/bin/ns-download
The URL has been changed after the project rename
> ns-install: fix repository URL

- config/ns-report.conf
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.dpireport
- packages/ns-api/files/ns.dpireport.json
- packages/ns-report/Makefile
- packages/ns-report/README.md
- packages/ns-report/files/20_ns-report
- packages/ns-report/files/dpireport
- packages/ns-report/files/dpireport-cleanup
- packages/ns-report/files/dpireport.init
Lightsquid-like reports based on netifyd data streams.
> ns-report: add dpireport daemon

- packages/ns-api-server/README.md
- packages/ns-api-server/files/ns-api-server.initd
- packages/ns-ui/Makefile
- packages/ns-ui/README.md
- packages/ns-ui/files/00ns.locations
- packages/ns-ui/files/99_ns-ui
- packages/ns-ui/files/config
- packages/ns-ui/files/ns-ui
Allow to change UI port if the 443 port must be forwarder to another server
> Dynamic LuCI and ns-ui port configuration

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.subscription
- packages/ns-api/files/ns.subscription.json
- packages/ns-plug/Makefile
- packages/ns-plug/files/ns-plug
- packages/ns-plug/files/register
- packages/ns-plug/files/subscription-info
New APIs:
- register
- unregister
- info
> Register APIs

- packages/ns-api/README.md
- packages/ns-api/files/ns.firewall
- packages/ns-api/files/ns.firewall.json
- packages/python3-nethsec/Makefile
Using new apis provided by NethServer/python3-nethsec#5, provide functions to ubus.
To be merged after NethServer/python3-nethsec#5
> Added zones/forwardings api to ubus

- .github/workflows/update-ns-ui.yml
nethsecuirity-ui now uses tags
> ci: use tag in ns_ui workflow

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.redirects
- packages/ns-api/files/ns.redirects.json
Implement APIs for port forwards.
> Redirect (port forwards) APIs

- packages/ns-api/README.md
- packages/ns-api/files/ns.subscription
- packages/ns-plug/files/register
- packages/ns-plug/files/subscription-info
- Subscription info: don't throw an error if there is no subscription
- Subscription register: write UCI database only after a successful registration
- Fix documentation
> Fix subscription API & doc

- packages/ns-api/README.md
Minor fixes to `ns.redirects` documentation
> ns-api: fix ns.redirects doc

- packages/ns-api/Makefile
- packages/ns-api/files/ns.mwan
- packages/ns-api/files/ns.mwan.json
- packages/python3-nethsec/Makefile
To be merged after: NethServer/python3-nethsec#7
> Added mwan APIs

- packages/ns-api/README.md
- packages/ns-api/files/ns.firewall
- packages/python3-nethsec/Makefile
Add `edit_zone` API to `ns-api`
> ns-api: edit firewall zones

- packages/ns-api/README.md
- packages/ns-api/files/ns.dedalo
- packages/ns-dedalo/files/ns-dedalo-setup
- packages/ns-dedalo/files/unregister_dedalo
https://trello.com/c/w3HUJq4r/132-hotspot-apis
> Dedalo APIs

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.flashstart
- packages/ns-api/files/ns.flashstart.json
https://trello.com/c/5gPBuC4u/137-flashstart-api
> ns-api: added flashstart api

- config/base-utils.conf
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.storage
- packages/ns-api/files/ns.storage.json
- add storage API
- add lsblk package required by the API
> Storage API

- packages/ns-api/README.md
- packages/ns-api/files/ns.dhcp
- packages/ns-api/files/ns.dns
- ns.dhcp: API
- ns.dns: fix API
- fix documentation
> ns-api: fix ns.dhcp & ns.dns

- packages/ns-api/README.md
- packages/python3-nethsec/Makefile
Updated doc due to related `python3-nethsec` update.
> DPI API update

- packages/ns-api/files/ns.dedalo
Requires python3-nethsec >= 0.0.10
Card: https://github.com/NethServer/nethsecurity/pull/197
See also: https://github.com/NethServer/python3-nethsec/pull/15
> ns-api: ns.dedalo, implement list_devices

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.backup
- packages/ns-api/files/ns.backup.json
Added APIs for:
- set passphrase
- backup
- restore (with or without password)
- remote backup list
- remote backup
- remote restore (with or without password)
- download remote backup
> ns-api: add backup APIs

- packages/ns-api/README.md
- packages/python3-nethsec/Makefile
- python3-nethsec: bump version to 0.0.13
- ns-api: updated doc for ns.dpi
Ref: NethServer/python3-nethsec#17
> DPI category file fix

- packages/ns-api/README.md
- packages/ns-api/files/ns.ovpntunnel
- packages/ns-migration/files/scripts/openvpn_tunnels
- packages/openvpn-easy-rsa/Makefile
- packages/openvpn-easy-rsa/files/openvpn-easy-rsa.profile
- packages/openvpn-easy-rsa/files/openvpn-easy-rsa.upgrade
- packages/openvpn-easy-rsa/patches/100-Make-package-reproducible.patch
Card: https://trello.com/c/TMCddZPm/155-openvpn-tunnel
See also https://github.com/NethServer/nethserver-firewall-migration/pull/21
> API: OpenVPN tunnels

- config/acme.conf
23.05 new implementation changed config name
Card: https://trello.com/c/JVZIAZhf/196-fix-acme-dns-package
> config: fix acme dns

- packages/ns-migration/files/scripts/openvpn_tunnels
Card: https://trello.com/c/oM24VF2z/164-fix-openvpn-and-ipsec-tunnel-migration
> ns-migration: fix openvpn tunnels

- packages/ns-api/README.md
- packages/ns-api/files/ns.dedalo
- packages/ns-dedalo/files/unregister_dedalo
- packages/python3-nethsec/Makefile
Card: https://trello.com/c/S501NOqz/167-hotspot-api-various-bugs
> ns-api: ns.dedalo, multiple fixes

- packages/ns-api-server/files/ns-api-server.initd
Merge after: https://github.com/NethServer/nethsecurity-api/pull/2
> ns-api-server. added ENVs for /upload API

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.factoryreset
- packages/ns-api/files/ns.factoryreset.json
> ns-api: add ns.factoryreset

- config/qemu.conf
Ease integration with KVM virtualization platforms like Proxmox
The image has increased nearly by 2 MB. 
Card: https://trello.com/c/qrZEb44x/205-add-qemu-ga-package
> conf: add qemu guest agent

- config/ipsec.conf
- files/usr/sbin/ns-upgrade
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.update
- packages/ns-api/files/ns.update.json
- packages/ns-api/files/schedule-system-update
- Add `ns.update` API
- Add `ns-upgrade` command to update the system to latest available image
> ns-api: add ns.update

- packages/ns-api/README.md
- packages/ns-api/files/ns.dhcp
Card: https://trello.com/c/dTaFNmqv/219-qa-dns-dhcp-various
> Minor DHCP API fixes

- packages/ns-api/README.md
- packages/ns-api/files/ns.dpi
- packages/ns-dpi/README.md
- packages/ns-dpi/files/dpi-config
Card: https://trello.com/c/BxNF70JT/168-dpi-add-exclusions-to-rule-global
Requires: https://github.com/NethServer/python3-nethsec/pull/20
> DPI global exemptions

- packages/ns-migration/files/scripts/wan
If use_member is not a list the index_policies function inside python3-nethsec package will break
> ns-migration: wan, make sure use_member is a list

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.devices
- packages/ns-api/files/ns.devices.json
Add `ns.devices` API
See: https://github.com/NethServer/nethsecurity-ui/pull/104
> ns-api: add interfaces and devices APIs

- packages/ns-api/files/ns.dedalo
- packages/ns-api/files/templates
- packages/ns-dedalo/files/ns-dedalo-setup
- packages/ns-dedalo/files/unregister_dedalo
Card: https://trello.com/c/PLUYWVKS/230-hospotqa
> Hotspot fixes

- packages/ns-api/files/ns.devices
Card: https://trello.com/c/6rK97Xuz/218-devices-and-interfaces-qa
> Network fixes

- packages/ns-api/README.md
- packages/ns-api/files/ns.devices
Add `list-zones-for-device-config` method to `ns.devices`. It lists all firewall zones that can be selected for device configuration
See also: https://github.com/NethServer/nethsecurity-ui/pull/118
> ns-api: add list-zones-for-device-config

- packages/ns-don/files/don
Disconnect after 7 days of inactivity to cleanup
stale connections
> ns-don: set inactive option

- packages/ns-api/files/ns.devices
Show OpenVPN Road Warrior servers in `list-devices` method of `ns.devices`
> ns-api: ns.devices, list openvpn rw servers

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.reverseproxy
https://trello.com/c/CdZUuXYy/265-reverse-proxy-certificate-management
> ns-api: certificate management APIs

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.firewall
- packages/python3-nethsec/Makefile
Card: https://trello.com/c/Qd0QkDLf/179-firewall-rules
Requires: https://github.com/NethServer/python3-nethsec/pull/27
> ns-api: firewall, rule APIs

- docs/distfeed.md
- files/usr/bin/ns-download
- files/usr/share/ns-plug/hooks/register/distfeed-setup
- files/usr/share/ns-plug/hooks/unregister/distfeed-setup
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.update
- packages/ns-api/files/schedule-automatic-updates
- packages/ns-plug/Makefile
- packages/ns-plug/files/distfeed-setup
Changes:
- add distfeed-setup script to automatically change repository channel on subscription events
- refactor ns-download to download the image from the correct channel
- add API to set and retrieve automatic updates status
Card: https://trello.com/c/f19Q3UAV/284-repository-and-versioning-refactor
> Improve updates management

- packages/ns-api/files/ns.update
> ns-api: execute long tasks in background

- packages/ns-api/Makefile
- packages/ns-api/files/ns.reverseproxy
- packages/ns-migration/files/scripts/reverse_proxy
- packages/python3-nethsec/Makefile
improved performance to list-proxies
fixed issue when listing proxies with pending certificates
moved all core functions of reverse proxy api to lib
using lib functions in reverse proxy migration to make everything omogeneous
- depends on: https://github.com/NethServer/python3-nethsec/pull/28
> Reverse Proxy migration revamp

- packages/ns-migration/files/scripts/wan
> ns-migration: wan, set label

- packages/ns-migration/Makefile
- packages/ns-migration/files/scripts/network
Ran testing against migration, works fine
Should even correct and remove decimals due to int conversion
https://trello.com/c/8TeRLWxi/298-qos-bad-speed-migration
> ns-migration: fixed importing issue of QoS

- packages/ns-api/Makefile
- packages/ns-api/files/ns.ovpnrw
- packages/ns-api/files/ns.users
Fixes the following bugs:
- https://trello.com/c/iBVyucCW/307-openvpn-roadwarrior-authentication-failure-with-local-users
- https://trello.com/c/LBThdmRh/308-openvpn-configuration-lost-after-user-password-change
> Fix OpenVPN users management

- packages/ns-api/Makefile
- packages/ns-api/files/post-commit/restart-netdata.py
- packages/ns-plug/files/mwan.chart.py
The mwan chart inside netdata is not shown after multi wan configuration.
Card: https://trello.com/c/t4hn8exM/248-mwan-netdata-chart-not-showing
> ns.api: post-commit, restart netdata

- packages/ns-api/Makefile
- packages/ns-api/files/ns.mwan
- packages/python3-nethsec/Makefile
Adding call from `mwan` python module
Ref: https://trello.com/c/IfL8EN6X/306-multiwan-default-policy-single-wan
> ns-api: added clear_config api call

- config/snmp.conf
https://github.com/NethServer/nethsecurity-docs/pull/37
> config: add snmpd

- packages/ns-dpi/Makefile
- packages/ns-dpi/files/20_dpi
Make sure dpi config is preserved across upgrades
Card: https://trello.com/c/KWr9j3aR/321-dpi-filter-settings-lost-after-upgrade
> ns-dpi: mark configuration file

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.threatshield
- packages/ns-api/files/ns.threatshield.json
- packages/ns-threat_shield/Makefile
- packages/ns-threat_shield/files/banip.nethesis.feeds
Card: https://trello.com/c/UbzjFAwP/314-threat-shield-ip-minimal-ui
> ThreatShield APIs

- packages/ns-api/README.md
Ref: https://trello.com/c/ZqV1tbvf/268-docs-missing-ns-api-nsmwan-docs
> ns-api: added missing mwan documentation

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.netmap
- packages/ns-api/files/ns.netmap.json
Card: https://trello.com/c/tavYHA5b/283-nat-rules-source-and-destination-netmap
Requires: https://github.com/NethServer/python3-nethsec/pull/35/
> ns-api: add netmap

- packages/ns-api/files/ns.dashboard
Card: https://trello.com/c/UJBBGIJJ/117-dashboard-counters
> ns-api: dashboard, add banip counter

- packages/ns-api/files/ns.reverseproxy
Operation now is without rollback.
> ns-api: cleaning up acme after delete of certificate

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.plug
- packages/ns-api/files/ns.plug.json
- packages/ns-plug/README.md
- packages/ns-plug/files/config
- packages/ns-plug/files/ns-plug
Connect the unit to the controller.
> API: ns-plug for controller

- packages/ns-api/Makefile
- packages/ns-api/files/ns.dashboard
- packages/ns-api/files/ns.firewall
- packages/ns-api/files/post-commit/configure-netifyd.py
- packages/python3-nethsec/Makefile
Adopt changes coming from 
- NethServer/python3-nethsec#38
- NethServer/python3-nethsec#39
Card: https://trello.com/c/LFCTBvU7/351-aliases-among-interfaces
> Hide aliases

- packages/ns-dpi/files/dpi.init
Download netify apps and categories on boot.
https://trello.com/c/tWClJOWa
> ns-dpi: download netify apps on boot

- packages/ns-api/README.md
- packages/ns-api/files/ns.plug
- packages/ns-plug/README.md
- packages/ns-plug/files/ns-plug
Authenticate the register API using the registration token
Card: https://trello.com/c/a8ijOQlj/376-controller-improve-registration-security
> ns-plug: use registration token

- packages/ns-api/files/ns.subscription
- packages/ns-api/files/ns.threatshield
- packages/ns-plug/Makefile
- packages/ns-plug/files/subscription-info
Cards:
- https://trello.com/c/qyIEokkF/375-missing-connectivity-threat-shield
- https://trello.com/c/mM98o2wl/374-missing-connectivity-backup-panel
- https://trello.com/c/aToWlJ0j/373-missing-connectivity-subscription-panel
> API and subscription: gracefully handle missing Internet connection

- packages/ns-api-server/files/ns-api-server.initd
- packages/ns-api/README.md
- packages/ns-api/files/ns.backup
- packages/ns-api/files/ns.migration
ubus/rpcd can't handle large files:
all APIs fails with exit code 5 if the payload size is greater than ~70KB. Also rpcd dies if f the payoload size is greater then 1MB.
Changed APIs:
- ns.migration
- ns-backup
Card: https://trello.com/c/k0b38yGx/380-ubus-fails-to-handle-files-larger-than-70k
> ns-api: avoid upload/download of big files

- packages/ns-phonehome/README.md
Add link to privacy policy, improve info about collected data.
> ns-phonehome: doc, add privacy policy

- packages/ns-flashstart/files/flashstart-apply
Fix dns ip address and name reference
> Flashstart fix dns ip address

- packages/ns-api/README.md
- packages/ns-api/files/ns.controller
Functions for bulk actions from the controller:
- add-ssh-key
- remove-ssh-key
> ns-api: controller, manage SSH keys

- packages/ns-ui/Makefile
Allow to save changes for the policy URL
Card: https://trello.com/c/AvpCIK5s/82-ui-login-privacy-policy
See also: https://github.com/NethServer/nethsecurity-ui/pull/232
> ns-ui: add branding to conf files

- docs/design/api.md
- packages/ns-api/files/api-cli
The api-cli was broken when LuCI was disabled.
> api-cli: fix command

- packages/acme-common/Makefile
- packages/acme-common/files/acme-notify.sh
- packages/acme-common/files/acme.config
- packages/acme-common/files/acme.init
- packages/acme-common/files/acme.uci-defaults
- packages/acme-common/files/functions.sh
Version 1.0.4 from 23.05.3 branch contains an invalid config file. Switching to version 1.1.1 from master branch that fixes the issue.
Card: https://trello.com/c/ODg4cSnz/406-reverse-proxy-page-not-working
> packages: add acme-common

- packages/ns-api/README.md
- packages/ns-api/files/ns.users
- packages/python3-nethsec/Makefile
See also:
- https://github.com/NethServer/python3-nethsec/pull/41
- https://github.com/NethServer/nethsecurity-ui/pull/231
TODO:
Card: https://trello.com/c/RObKqXE2/404-users-database-allow-authenticated-access
> ns-api: users, support LDAP bind

- packages/acme-acmesh/Makefile
- packages/acme-acmesh/files/hook.sh
- packages/acme-common/files/acme.init
- packages/ns-api/files/ns.reverseproxy
> Fix Let's Encrypt certificate request

- packages/ns-api/Makefile
> ns-api: bump to 0.0.61

- packages/ns-api/files/ns.threatshield
Make sure changes to the allowlist are applied just after the save
#426
> ns-api: threatshield, force banip reload

- packages/ns-api/Makefile
- packages/ns-flashstart/Makefile
> Bump ns packages

- packages/ns-migration/files/scripts/ipsec
The link was pointing to a non-existing tunnel.
#431
> ns-migration: ipsec, fix ns_link

- packages/ns-api/files/ns.ipsectunnel
- packages/ns-migration/files/scripts/ipsec
Having multiple children tunnel should allow charon to correctly route traffic if the tunnel is connecting multiple networks
See also:
- https://github.com/NethServer/nethsecurity/issues/449
- https://github.com/NethServer/nethserver-firewall-migration/pull/34
#449
> ns-api: ipsec, create multiple children tunnels

- packages/ns-api/README.md
- packages/ns-api/files/ns.routes
The flag is set to false if the route has been generated from an IPSec tunnel
#450
> ns-api: routes, add editable flag

- packages/ns-api/README.md
- packages/ns-api/files/ns.dhcp
When force option is set, the DHCP server will be started even if there is already another server on the same network segment.
#454
> ns-api: dhcp, add force option

- packages/ns-api/files/ns.ovpnrw
It's easier to explore the list when sorted.
Card: https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=60675328
> ns-api: ovpnrw, sort users by username

- packages/ns-api/files/ns.users
Make sure to execute the same query of list-users.
> ns-api: users, pass schema to test-ldap

- config/arpscan.conf
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.scan
- packages/ns-api/files/ns.scan.json
> Scan network

- packages/ns-api/files/ns.reverseproxy
Closes https://github.com/NethServer/nethsecurity/issues/481
> ns-api: fix reverse proxy allowed ips when editing

- packages/ns-api/files/ns.mwan
Wait for:
Closes: NethServer/nethsecurity#469
> Add sync between MWAN setting and already active interfaces

- packages/ns-dpi/Makefile
- packages/ns-dpi/files/70dpi
> ns-dpi: remove signatures on register

- packages/ns-api/README.md
- packages/ns-api/files/ns.dashboard
Card: https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=59394165
> ns-api: dashboard, expose ovpnrw counter

- packages/ns-api/README.md
- packages/ns-api/files/ns.dashboard
Card: https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=59394165
> ns-api: dashboard, add ipsec-tunnels counter

- packages/ns-migration/README.md
- packages/ns-migration/files/ns-import
- packages/ns-migration/files/scripts/threat_shield
> Fix threat shield migration

- packages/python3-nethsec/Makefile
> python3-nethsec: bump release

- .github/workflows/release-stable.yml
Fixed missing `rclone` dependency
> ci: fixed missing rclone

- packages/ns-ui/README.md
> fix typo in api restart

- packages/python3-nethsec/Makefile
https://github.com/NethServer/nethsecurity/issues/556
> update package version to 0.0.58

- packages/ns-storage/files/ns-storage-setup-partition
Potential fix
https://github.com/NethServer/nethsecurity/issues/584
> ns-storage: handle nvme

- packages/ns-api/README.md
- packages/ns-api/files/ns.mwan
Add sticky options to store_rule and edit_rule
Merge after:
- https://github.com/NethServer/python3-nethsec/pull/50
https://github.com/NethServer/nethsecurity/issues/581
> Add 'sticky' field to API request parameters

- packages/ns-api/Makefile
- packages/ns-migration/Makefile
- packages/ns-plug/Makefile
- packages/ns-storage/Makefile
Bump ns-packages that has not still been released
> chore: bump ns packages (automatic)

- packages/ns-api/README.md
- packages/ns-api/files/ns.users
- packages/ns-objects/README.md
- packages/ns-openvpn/files/openvpn-remote-auth
- packages/python3-nethsec/Makefile
Implement user_bind_dn parameter: #602
Changes:
> Improve AD authentication

- packages/ns-api/files/ns.ipsectunnel
A regression has been introduced when multiple tunnels were created for each subnet
Ref:
- https://github.com/NethServer/nethsecurity/issues/615
> ns-api: fixing some values falling back to default

- packages/ns-api/README.md
- packages/ns-api/files/ns.users
- packages/ns-objects/README.md
- packages/python3-nethsec/Makefile
> Improve LDAP auth

- packages/ns-api/files/ns.ovpntunnel
> ns-api: added remote-cert-tls option in client configuration

- packages/ns-api/files/ns.threatshield
Changes:
- check entitlement validity by trying to download the whitelist
- fix level for DNS threat shield categories
- refactor level and use the same function for both DNS an IP services
> Threat shield community

- packages/ns-api/files/ns.subscription
Return also subscription type: the new
field can be used from the UI to display
Enterprise-only features
#653
> ns-api: improve ns.subscription

- packages/ns-api/files/ns.ovpnrw
The ip address was not removed when empty.
#661
> ns-api: ovpnrw, fix IP reservation

- packages/ns-api/README.md
- packages/ns-api/files/ns.ovpnrw
- packages/ns-migration/files/scripts/openvpn
See https://github.com/orgs/NethServer/projects/10?pane=issue&itemId=71949958
#678
> OpenVPN Pool

- packages/ns-api/README.md
- packages/ns-api/files/ns.redirects
The list_object_suggestion was returning unsupported objects
#689
> Fix redirect APIs

- packages/ns-api/files/ns.reverseproxy
- packages/ns-ui/files/ns-ui
> Default certificate for ns-ui

- packages/ns-api/files/templates
- packages/ns-migration/files/scripts/network
> Improve guest zone migration

- config/usb_serial.conf
Limited support for USB to serial devices.
#711
> conf: add USB to serial support

- packages/ns-api/files/ns.reverseproxy
Ref: 
- https://github.com/NethServer/nethsecurity/issues/723
> ns-api(reverse proxy): touchups to api to fix UI bug

- packages/ns-api/Makefile
- packages/ns-api/files/ns.controller
Ref:
- https://github.com/NethServer/nethsecurity/issues/721
> ns-api(controller): adding ui_version to the info sent to controller

- packages/ns-api/Makefile
Ref:
- https://github.com/NethServer/nethsecurity/issues/724
> ns-api: add nathelpers apis to makefile

- packages/ns-api/files/ns.nathelpers
Ref:
- https://github.com/NethServer/nethsecurity/issues/724
> ns-api: fix nat helpers api

- packages/ns-ui/files/ns-ui
Fixing issue regarding being unable to disable luci when updating the image
Ref:
- #760
> ns-ui: fixed issue with being unable disable luci interface

- packages/ns-migration/files/scripts/openvpn_tunnels
> ns-migration: truncate tun names to max 15 chars

- packages/ns-api/files/ns.reverseproxy
> ns-api: fixed missing import in reverse proxy api

- .github/workflows/release-stable.yml
Getting the MAJOR from the latest annotated tag.
> ci: removing hardcoded MAJOR

- packages/ns-ui/files/ns-ui
> ns-ui: fix nginx include

- packages/ns-api/README.md
- packages/ns-api/files/ns.plug
- packages/ns-plug/files/ns-plug
- packages/ns-plug/files/ns-push-reports
Changes:
- send data only if subscription is enabled
- add push info to the ns.plug status API
- log ns-push-reporta failure
#754
> Improve historical data sending

- packages/ns-api-server/Makefile
- packages/ns-api/Makefile
> PR issue #810

- config/qemu.conf
- config/vmware.conf
> Hypervisor tools as optional packages

- packages/ns-api/README.md
- packages/ns-api/files/ns.firewall
Issue #807
Requires: https://github.com/NethServer/python3-nethsec/pull/70
> ns-api: firewall, add log field for zones

- files/etc/uci-defaults/99-nethsec-mwan
- packages/python3-nethsec/Makefile
Ref:
- https://github.com/NethServer/nethsecurity/issues/853
> fix: setting default mwan last_resort

- packages/ns-api/README.md
- packages/ns-api/files/ns.ovpnrw
This pull request adds an API for retrieving the last user connections and the connection history in CSV format.
Refs:
- https://github.com/NethServer/nethsecurity/issues/869
> Add API for history connections

- packages/ns-api/files/ns.redirects
- packages/python3-nethsec/Makefile
Refs:
- https://github.com/NethServer/nethsecurity/issues/895
> fix(ns-api): removed linked references to redirect

- packages/ns-api/files/ns.objects
> fix(ns-api): extend timeout of domain set records

- packages/ns-api/files/ns.report
Add `ns.report` `get-public-ip-addresses` API
Ref:
- https://github.com/NethServer/nethsecurity/issues/890
> feat(ns-api): add ns.report get-public-ip-addresses

- packages/ns-api/files/ns.dpireport
Due to changes needed for filtering in https://github.com/NethServer/nethsecurity/issues/937 the code was refactored to offer the functionality needed for the UI feature implementation.
~~To avoid issues, merge only after implementation coming from https://github.com/NethServer/nethsecurity/issues/900.
This can, in fact, be safely added as an additional feature while deprecating the other API to avoid breaking changes.~~
The old `summary` has been backported, this can be safely merged.
> refactor(ns-api): refactored dpi report stats reporting

- packages/ns-plug/files/send-backup
This reverts commit d1d4204225b755876c368fc7eda0829da1dc0ba9.
> Revert "ns-plug: remove hack for acme backup (#364)"

- packages/ns-migration/files/scripts/openvpn
Ref:
- https://github.com/NethServer/nethsecurity/issues/991
> fix(migration): skipping invalid users while migrating openvpn

- packages/ns-api/README.md
- packages/python3-nethsec/Makefile
Ref:
- https://github.com/NethServer/nethsecurity/issues/997
> chore(python3-nethsec): version bump and doc update

- packages/ns-api/README.md
- packages/ns-api/files/ns.snort
- packages/snort3/Makefile
- packages/snort3/README.md
- packages/snort3/files/ns-bypass-config
- packages/snort3/files/snort.init
- Added APIs to handle bypass listing, creation and deletion
- Added additional file to handle bypasses creation instead of inside procd file
> feat(ips): added bypass APIs

- packages/ns-api/README.md
- packages/ns-api/files/ns.snort
Added APIs for IPS rule management
- Added listing of disabled rules
- Added delete of disabled rules
- Added creation of disabled rules
Ref: https://github.com/NethServer/nethsecurity/issues/1017
> feat(ips): adding rules management

- packages/ns-api/README.md
- packages/ns-api/files/ns.snort
Ref:
- https://github.com/NethServer/nethsecurity/issues/1018
> feat(ips): adding suppression alerts

- packages/ns-api/README.md
- packages/ns-api/files/ns.threatshield
- Return port list in `dns-list-settings` API
- Add DNS local blocklist apis
- Fix dns-edit-settings
- Remove unused variable
- Update dns threat shield README
Ref:
- https://github.com/NethServer/nethsecurity/issues/906
> fix(ns-api): fix threat shield dns apis

- packages/ns-api/README.md
- packages/ns-api/files/ns.snort
- Hammered down few bugs
- Removed composed ID
- Added list-events api
Ref:
- https://github.com/NethServer/nethsecurity/issues/1016
> feat(ips): added event page

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.snort
- packages/ns-ui/Makefile
- packages/snort3/Makefile
- packages/snort3/README.md
- packages/snort3/files/ns-bypass-config
- packages/snort3/files/ns-snort-rules
- packages/snort3/files/snort.init
Added relevant APIs to handle IPS management through UI.
NOTE: this is a PR that groups all the changes approved in previous ones. Only addon is the correct bump version.
> feat: added IPS APIs

- packages/ns-api/README.md
- packages/ns-ui/Makefile
- packages/python3-nethsec/Makefile
Ref:
- https://github.com/NethServer/nethsecurity/issues/989
> fix(firewall): allow rules with same src/dest zone

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.ssh
First steps towards: https://github.com/NethServer/nethsecurity/issues/1023
> refactor(ns-api): removed `file` calls for SSH keys

- packages/ns-openvpn/files/80-save-connection
> fix(ns-openvpn): history, always get correct virtual IP

- packages/ns-api/files/ns.ovpntunnel
Ref:
- https://github.com/NethServer/nethsecurity/issues/1037
> fix(ns-api): exporting multiple RemoteHosts for tunnel

- packages/ns-plug/files/mwan-hooks
https://github.com/NethServer/nethsecurity/issues/1054
> fix(ns-plug): treat SIGHUP as non-error in mwan signaling

- packages/libdaq3/Makefile
- packages/snort3/Makefile
- packages/snort3/patches/100-remove-HAVE_HS_COMPILE_LIT-to-work-around-upstream-b.patch
- packages/snort3/patches/110-packet_capture-Fix-compilation-with-GCC-13.patch
Ref:
- https://github.com/NethServer/nethsecurity/issues/1074
> build(snort3): update snort package

- packages/ns-api/files/ns.account
- packages/ns-ui/Makefile
- packages/python3-nethsec/Makefile
Reinforce password change asking for old user password
Needs:
- https://github.com/NethServer/python3-nethsec/pull/92
UI:
- https://github.com/NethServer/nethsecurity-ui/pull/513
> fix(ns-api): ask for old password before changing it

- packages/ns-api-server/Makefile
Ref:
- https://github.com/NethServer/nethsecurity/issues/1075
> chore(ns-api-server): version bump

- packages/ns-api/files/ns.dhcp
Ref:
- https://github.com/NethServer/nethsecurity/issues/1089
> fix(dhcp): validate that first and last ip doesn't include interface

- patches/feeds/packages/100-snmpd-default-disable.patch
Ref:
- https://github.com/NethServer/nethsecurity/issues/1028
> fix(snmpd): disable config by default

- packages/banip/Makefile
- packages/banip/files/README.md
- packages/banip/files/banip-functions.sh
- packages/banip/files/banip-service.sh
- packages/banip/files/banip.cgi
- packages/banip/files/banip.conf
- packages/banip/files/banip.countries
- packages/banip/files/banip.feeds
- packages/banip/files/banip.init
- packages/banip/files/banip.tpl
Ref:
- https://github.com/NethServer/nethsecurity/issues/1096
> build: forked banip

- packages/ns-api/README.md
- packages/ns-api/files/ns.dhcp
Ref:
- https://github.com/NethServer/nethsecurity/issues/973
> feat(ns-api): added MAC binding to API calls

- packages/ns-api/files/ns.redirects
The custom log_limit was lost after an edit
NethServer/nethsecurity#1105
> fix(ns-api): redirects, preserve custom log_limit

- packages/ns-plug/files/ns-plug
Ref:
- https://github.com/NethServer/nethsecurity/issues/1115
> fix(ns-plug): configure promtail at every initial connection

- docs/build/custom_images.md
See https://community.nethserver.org/t/hey-guys-i-was-build-a-nethsecurity-firmware/25542/8
> doc: fix imagebuilder link

- packages/banip/files/README.md
- packages/banip/files/banip.feeds
Ref:
- https://github.com/NethServer/nethsecurity/issues/1127
> fix(banip): remove nixspam list

- packages/ns-api/files/ns.flashstart
- packages/ns-flashstart/Makefile
- packages/ns-flashstart/files/flashstart-setup-firewall
- packages/ns-flashstart/files/uci-default
Ref:
- https://github.com/NethServer/nethsecurity/issues/1125
> fix(flashstart): allow firewall to bypass flashstart

- config/nmap.conf
Ref:
- https://github.com/NethServer/nethsecurity/issues/1129
> build: added nmap package

- packages/ns-migration/files/scripts/dns
Ref:
- https://github.com/NethServer/nethsecurity/issues/1131
> fix(ns-migration): create domains related to wildcards

- packages/ns-dpi/files/dpi-nft
Avoid kernel hang, if the firewall has many DPI rules and the the logging is enabled.
NethServer/nethsecurity#1140
> fix(dpi): honor log limit

- scripts/announce_updates.py
Previously the script was generating an empty announce during days when only pull requests were closed.
> fix(announce_updates): exclude PRs

- packages/ns-migration/files/ns-import
Ref:
- https://github.com/NethServer/nethsecurity/issues/1135
> fix(ns-migration): configure netifyd on migration

- packages/ns-api/files/ns.talkers
The UI expects a rate and not a sum of total bytes.
#1094
> fix(ns-api): talkers, calculate app and proto rate

- packages/ns-api/files/ns.threatshield
> fix(ns-api): cleanup threat shield initial fields 

- config/bonding.conf
- config/luci.conf
Removed luci-proto-bonding, added package proto-bonding
#1166
> fix: replaced bonding

- packages/ns-api/files/ns.redirects
Changes:
- revert commit 0347489c843fea23d897ac98dc361012aa02df0c.
- add GRE protocol
#1177
> feat(ns-api): redirects, support gre protocol

- packages/ns-plug/Makefile
- packages/ns-plug/README.md
- packages/ns-plug/files/20_ns-plug
- packages/ns-plug/files/backup-encryption-alert
Send an alert if the backup is not encrypted
Active backup:
Resolved alert:
#1119
> feat(ns-plug): add backup alert

- packages/ns-api-server/Makefile
- packages/ns-ui/Makefile
1. Trigger the SSH Add or Remove action.
2. Verify the password prompt behavior (see "Password Prompt Behavior" section below).
- Enable 2FA  
- Retrieve Recovery Codes  
- Disable 2FA
For each action:
1. Ensure the feature functions as expected.
2. Verify the password prompt behavior (see below).
---
For any sensitive action that triggers password verification:
1. A password prompt/modal must appear.
2. Enter the correct password – authentication should succeed.
3. Dismiss the modal and retry the action – it should work without issues.
4. When prompted again, enter a wrong password – the form should clearly show an error message.
5. Password should only be required once every 5 minutes.
---
- 2FA features have been heavily refactored.
- Make sure enabling, retrieving recovery codes, and …
> implementing sudo mode

- packages/ns-ha/README.md
some improvement to the readme document.
> keepalived readme changes

- packages/ns-api/files/ns.ovpntunnel
This applies both to NS7 and NS8
https://github.com/NethServer/nethsecurity/issues/1188
> fix(ns-api): fixed import/export of ovpn tunnel

- packages/ns-api/Makefile
- packages/ns-api/files/ns.ipsectunnel
- packages/ns-api/files/uci-defaults/99-ns-api.ipsec
Always retry reconnection of IPSec VPN
Ref: #1179
> fix(ipsec): clients should retry indefinitely

- packages/ns-api/files/ns.dashboard
Ref: https://github.com/NethServer/nethsecurity/issues/1206
> fix:(ns-api): removed kernel filtering, just count banned ips

- files/etc/uci-defaults/29-ns-storage-default
Enable storage on extra partition on boot device only if not USB.
https://github.com/NethServer/nethsecurity/issues/1082
> feat(ns-storage) enable storage by default

- packages/ns-api/Makefile
- packages/ns-api/files/uci-defaults/99-ns-api.dropbear
Closes https://github.com/NethServer/nethsecurity/issues/1222
> fix(ssh): renamed uci instance from no name to main

- packages/ns-api/files/ns.subscription
- packages/ns-plug/Makefile
- packages/ns-plug/files/send-inventory
- packages/ns-plug/files/send-inventory.init
Closes https://github.com/NethServer/nethsecurity/issues/1176
> feat: added last inventory sent info

- packages/ns-migration/files/ns-import
> feat(ns-import): add version to migration log

- packages/ns-api/files/ns.ovpnrw
Windows are client are bugged and can't correctly handle reneg_sec
Closes #1236
> ns-api(ovpnrw): always disable reneg_sec

- packages/ns-plug/Makefile
- packages/ns-plug/files/send-inventory
Due to the rebase made by https://github.com/NethServer/nethsecurity/issues/1295 date formatting changed, causing issues in the timestamp saved for the UI.
> fix(ns-plug): date formatting changed with 24.10.2

- packages/ns-api/files/ns.redirects
> fix(port forward): do not disable external object through the kebab menu

- packages/ns-api/files/ns.firewall
- packages/python3-nethsec/Makefile
Closes: https://github.com/NethServer/nethsecurity/issues/1291
Needs: https://github.com/NethServer/python3-nethsec/pull/103
> feat(rules): added link

- docs/design/distfeed.md
Updated how management of upstream openwrt packages should be made.
Also changed how now management of packages happens.
> docs: updated documentation due to new management of builds

- config/etherwake.conf
> feat: add etherwake extra package

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.plug
Issues arised when deploying controller v2, the inability to edit the description field might appear troublesome for some users.
Refs:
- https://partner.nethesis.it/t/controller-2-0-0/9590
- https://helpdesk.nethesis.it/a/tickets/193603
> feat(ns-plug): added ability to update description without disconnetting

- packages/ns-api/Makefile
- packages/ns-api/files/misc/wireguard-migrate.py
- packages/ns-api/files/ns.wireguard
- packages/ns-api/files/uci-defaults/99-ns-api.wireguard
- **added migration from old config**
- **adjustments to APIs**
> fix(wireguard): adjustments pre-release
