- config/ns-rsyslog.conf
- config/rsyslog.conf
- files/etc/uci-defaults/99-nextsec-rsyslog
- packages/ns-rsyslog/Makefile
- packages/ns-rsyslog/files/config
- packages/ns-rsyslog/files/ns-rsyslog.init
- Add ns-rsyslog
- Remove logd and logread
- Support dynamic configuration with UCI
Default rsyslog configuration:
- send everything to /var/log/messages
- UDP and TCP receiver are disabled
Setup forwarding to promtail:
```
uci set rsyslog.promtail=forwarder
uci set rsyslog.promtail.source=*.*
uci set rsyslog.promtail.protocol=tcp
uci set rsyslog.promtail.port=10514
uci set rsyslog.promtail.rfc=5424
uci set rsyslog.promtail.target=192.168.122.2
uci commit
/etc/init.d/rsyslog restart
```
Setup forwarding to another rsyslog:
```
uci set rsyslog.promtail=forwarder
uci set rsyslog.promtail.source=*.*
uci set rsyslog.promtail.protocol=udp
uci set rsyslog.promtail.port=10514
uci set rsyslog.promtail.rfc=3164
uci set rsyslog.promtail.target=192.168.122.2
uci commit
/etc/init.d/rsyslog restart …
```
> Improved logging, new ns-rsyslog package

- config/luci.conf
banip has been marked as blocked because not compatible with fw4
See https://github.com/openwrt/packages/commit/a2f02572726d4659cd3f5e28387094b263dc6b74
> luci: remove banip

- files/etc/uci-defaults/99-nextsec-webui
Simplify first configuration.
The UI should then guide the user to remove the firewall rule.
> config: open UI from WAN

- config/ns-migration.conf
- packages/ns-migration/Makefile
- packages/ns-migration/README.md
- packages/ns-migration/files/ns-import
- packages/ns-migration/files/scripts/dhcp
- packages/ns-migration/files/scripts/dns
- packages/ns-migration/files/scripts/fwutils.py
- packages/ns-migration/files/scripts/network
- packages/ns-migration/files/scripts/nsmigration.py
- packages/ns-migration/files/scripts/openvpn
- packages/ns-migration/files/scripts/redirects
- packages/ns-migration/files/scripts/routes
- packages/ns-migration/files/scripts/rules
- packages/ns-migration/files/scripts/ssh
- packages/ns-migration/files/scripts/subscription
- packages/ns-migration/files/scripts/threat_shield
- packages/ns-migration/files/scripts/time
- packages/ns-migration/files/scripts/wan
Add a new `ns-migration` package to handle the migration from NS7 firewall. 
Import:
- DHCP ranges
- DHCP static leases (reservations)
- Number of max leases
- Network configuration
- Firewall zones
- DNS records (local and remote)
- Machine hostname and domain
- Wildcard DNS records
- Static routes
- SSH configuration (with some limitation)
- NTP
- Timezone
- Subscription
- Port forward
- Threat shield (see also #29 and #24)
Following configurations are not currently migrated:
- Network bridges and bonds
- PPPoE WAN
- QoS rules and bandwitdh configuration
- Hotspot firewall role and hotspot application (dedalo)
- OpenVPN tunnels
- IPSec tunnels
See also NS7 configuration exporter: https://github.com/NethServer/nethserver-firewall-migration
> Migration draft package

- .github/workflows/build-image.yml
- config/images.conf
- docs/_config.yml
- docs/quickstart.md
```
CONFIG_IB=y
CONFIG_IB_STANDALONE=y
```
> Refactor unused images

- files/etc/uci-defaults/95-nextsec-migrate
Automatically call ns-import on /usr/share/migration/export.tar.gz. The script imports will be executed only on first boot and after the upgrade.
See also https://github.com/NethServer/nethserver-firewall-migration/pull/7
> files: add automatic import script

- config/acme.conf
- config/ns-reverse-proxy.conf
- files/etc/board.d/40virtual
- files/etc/uci-defaults/99-nextsec-webui
- packages/ns-migration/Makefile
- packages/ns-migration/README.md
- packages/ns-migration/files/ns-import
- packages/ns-migration/files/scripts/acme
- packages/ns-migration/files/scripts/reverse_proxy
- packages/ns-reverse-proxy/Makefile
- packages/ns-reverse-proxy/README.md
- packages/ns-reverse-proxy/files/nginx-proxy
See also https://github.com/NethServer/nethserver-firewall-migration/pull/9
> Reverse proxy and Let's Encrypt support

- packages/ns-migration/files/scripts/network
Currently, migrated aliases are not associated to any zone.
See also https://github.com/NethServer/nethserver-firewall-migration/pull/11
> ns-migration: add role to aliases

- packages/ns-threat_shield/Makefile
- packages/ns-threat_shield/files/20_threat_shield
- packages/ns-threat_shield/files/ts-dns.init
- packages/ns-threat_shield/files/ts-ip.init
Enable both Threat Shield services (ts-ip and ts-dns) using the standard START init variable.
Add cronjobs via uci-default.
Use procd for ts-ip init script to have a trigger to reload service on configuration change and a useful option to temporarily stop it without disabling the service.
This pull request replaces https://github.com/NethServer/nextsecurity/pull/47
> Threat shield startup fixes

- packages/ns-threat_shield/files/ts-ip-download
Sometimes at boot, ts-ip could fail the download of lists due to DNS issues.
The script now tries to download each category multiple times.
> ns-threat_shield: improve download code

- files/etc/uci-defaults/95-nextsec-migrate
- packages/ns-migration/README.md
Since the migration process is started before any logger is active, log all output to a log file
> ns-migration: log to file

- patches/feeds/packages/200-mwan3-disable.patch
mwan3 should be enabled only when there is a wan correctly configured with a metric, otherwise the connection marking could lead to non-routable connections
Also remove default config which usually is not applicable.
> packages: disable mwan3

- files/usr/sbin/menu
If a machine has been installed with dd, like VMs, hide the install options.
The fix should work also with machine with extra external storage.
The install option can still appear when connecting an extra storage which is not already mounted. This should be a temporary situtation and culd be ignored.
> menu: hide install options on installed machine

- config/ns-phonehome.conf
- packages/ns-phonehome/Makefile
- packages/ns-phonehome/README.md
- packages/ns-phonehome/files/20_ns-phonehome
- packages/ns-phonehome/files/config
- packages/ns-phonehome/files/phonehome
- packages/ns-phonehome/files/send-phonehome
Send statistical data to remote server.
The phonehome output can be used to create a database of all working hardware.
To list the PCI interfaces with relevant kernel module use:
```
phonehome | jq .facts.pci
```
> packages: add ns-phonehome

- patches/feeds/packages/100-nginx-buffer.patch
Restore nginx large_client_header_buffers default to "4 8k". OpenWrt default are too small for many sites when nginx is used as reverse proxy
> patches: change nginx large_client_header_buffers

- packages/ns-openvpn/Makefile
- packages/ns-openvpn/files/99_ns-openvpn
- packages/ns-openvpn/files/ns-openvpnrw-setup
If the package is already present inside the image, the postinst script is not executed.
The db initialization has been moved under uci-defaults which are executed at first boot
> ns-openvpn: fix db initialization

- packages/ns-migration/README.md
- packages/ns-migration/files/scripts/redirects
Luci doesn't handle redirects with ipset limitations
See also https://github.com/NethServer/nethserver-firewall-migration/pull/13
> ns-migration: drop ipset for redirects

- packages/ns-openvpn/README.md
- packages/ns-openvpn/files/99_ns-openvpn
- packages/ns-openvpn/files/ns-openvpnrw-setup
PKI initialization should be fast enouth with 'dsaparm' option for 'openssl dhparam'  command.
Other changes: do not recreate `allow-openvpnrw` rule across update to avoid overwriting user firewall setup
> ns-openvpn: execute setup on first boot and on upgrade

- docs/quickstart.md
- files/usr/libexec/login.sh
Since the menu is gone, this is and easy way to make sure keymap is already configured before login.
Replaces #100
> files: add persistent keymap configuration

- packages/ns-storage/Makefile
- packages/ns-storage/files/30_ns-storage
Logorate requires the path of configuration file as first parameter.
When executing logrotate from command line:
```
logrotate 3.17.0 - Copyright (C) 1995-2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU General Public License
Usage: logrotate [-dfv?] [-d|--debug] [-f|--force] [-m|--mail=command] [-s|--state=statefile] [--skip-state-lock] [-v|--verbose] [-l|--log=logfile] [--version]
[-?|--help] [--usage] [OPTION...] <configfile>
```
See also cron job script from `logrotate-3.8.6-19.el7.x86_64` RPM on CentOS 7:
```bash
#!/bin/sh
/usr/sbin/logrotate -s /var/lib/logrotate/logrotate.status /etc/logrotate.conf
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
/usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
```
> ns-storage: fix logrotate cronjob

- config/netdata.conf
- patches/feeds/packages/100-netdata-export-promethus.patch
Add Netdata to expose metrics in real time.
This is a modified version of netdata upstream package which enable prometheus export.
Netdata UI is available at `http://<server_ip>:19999`.
Prometheus export is available at `http:///<server_ip>:19999/api/v1/allmetrics?format=prometheus&help=yes`
> packages: add netdata

- packages/ns-threat_shield/README.md
- patches/feeds/packages/100-adblock-start-tsdns.patch
Make sure ts-dns is always executed, even after firmware flash. Otherwise after flashing, adblock will not start because /etc/adblock/combined.sources.gz is missing
> ns-threat_shield: force ts-dns execution

- packages/ns-dedalo/Makefile
The "dedalo" zone should only contain the dedalo interface. UCI defaults should not be executable.
Using `set` instead of `add_list` avoids the list growing on every update.
> ns-dedalo: fix UCI defaults

- packages/ns-api-server/Makefile
- packages/ns-api-server/files/ns-api-server.initd
Repository should be renamed to contain controller and stand-alone APIs.
> ns-api-server: download from nethsecurity-api repo

- packages/ns-api/Makefile
- packages/ns-api/files/ns.firewall
- packages/ns-api/files/ns.firewall.json
- packages/python3-nethsec/Makefile
List firewall rules preserving order.
The default uci call returns a firewall object.
Firewall object do not preserve the order.
> ns-api: add ns.firewall API

- packages/ns-plug/files/ns-plug
The new server controller written in go has new APIs. This PR adapts the `ns-plug` command to the new APIs:
- changed ns-plug command registration endpoint from `/servers/register` to `/units/register`
- adjusted json response attributes
> changed response data to match new APIs

- config/luci.conf
luci-app-openvpn is an old app dependant on luci-compat.
> packages: remove luci-app-openvpn

- packages/ns-threat_shield/Makefile
- packages/ns-threat_shield/files/20_threat_shield
We lost the threat shield crontab entries when we moved to banip.
Restore crontab entries.
> ns-threat_shield: fix crontab

- packages/ns-dpi/Makefile
- packages/ns-dpi/README.md
- packages/ns-dpi/files/20_dpi
- packages/ns-dpi/files/dpi-update
Download dpi signatures for netifyd:
- every night
- upon machine registration
Signatures are downloaded using an authenticated proxy.
The machine must have a valid subscription to access the proxy.
Available test proxy server: `sp.gs.nethserver.net`
To test the download:
```
HOST=http://__USER__:__PASSWORD__@sp.gs.nethserver.net bash -x dpi-update
```
> ns-dpi: add signature downloader

- packages/ns-plug/files/ns-plug
- packages/ns-plug/files/ns-plug.init
The ns-plug script was not connecting to the controller after reboot.
Changes:
- wait up to 60 seconds for the controller to become reachable
- make sure to output OpenVPN log to syslog
- restart rsyslog only if necessary
See https://trello.com/c/F3wP9buv/75-ns-plug-wont-connect-at-boot
> ns-plug: fix connect on boot

- packages/ns-api/files/ns.dpireport
Month and day are always padded with 0.
The API is now more robust and accept also input
parameters day and month without the leading zero.
> ns-api: better param handling on ns.dpireport

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.dpi
- packages/ns-dpi/files/dpi-config
- packages/python3-nethsec/Makefile
- renamed DPI parameter `interface` to `device`, removing every doubt that would have come up regards of what this field was supposed to contain
- added `list-devices` api and examples
Requiring `python3-nethsec:0.0.8` to work, please wait for NethServer/python3-nethsec#13 to be merged and tagged.
> Changes to DPI api

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.migration
- packages/ns-api/files/ns.migration.json
Card: https://trello.com/c/oWu4dI7P/163-migration-ui
> ns-api: add ns.migration

- packages/ns-api/files/ns.ovpntunnel
- packages/ns-migration/files/scripts/openvpn
- packages/ns-openvpn/Makefile
- packages/ns-openvpn/files/ns-openvpnrw-setup
- packages/ns-openvpn/files/openvpn-status
- packages/python3-nethsec/Makefile
> OpenVPN fixes

- config/netdata.conf
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.netdata
- packages/ns-api/files/ns.netdata.json
Changes:
- add ns.netdata API: manage fping plugin
- add netdata proxy pass, netdata is now available at `https://<fqdn>/netdata`
Replaces #213 
Card: https://trello.com/c/oNd1oPPW/134-ping-latency-monitor
> Report api

- otp.conf
- packages/ns-migration/README.md
- packages/ns-migration/files/scripts/openvpn
- packages/ns-openvpn/Makefile
- packages/ns-openvpn/README.md
- packages/ns-openvpn/files/ns-openvpnrw-print-client
- packages/ns-openvpn/files/openvpn-otp-auth
TODO:
See also:
- https://github.com/NethServer/nethserver-firewall-migration/commit/1b165f7fa81a615c21c0fbffd86632310dd40b64
- https://github.com/NethServer/nethserver-firewall-migration/commit/22593ce43356bbd42f60b0a345e292457b6e9737
-
> OpenVPN: OTP authentication + client export improvements

- packages/openssh/Config.in
- packages/openssh/Makefile
- packages/openssh/files/sftp-ssh.service
- packages/openssh/files/sshd.failsafe
- packages/openssh/files/sshd.init
- packages/openssh/files/sshd.pam
- packages/openssh/files/sshd.pam-access
- packages/openssh/patches/900-sshd_config-include-dir.patch
Card: https://trello.com/c/OFfbXifR/224-openssh-listening-on-port-22
Possible implementations:
- fork the package and disable the service
- change the port and create a crash loop: `echo  "Port 0" >> /etc/ssh/sshd_config.d/disable_default_port.conf`
This PR implements the first proposal
> OpenSSH fix: disable listening on port 22

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.ssh
- packages/ns-api/files/ns.ssh.json
Card: https://trello.com/c/ZymrMQnR/226-ssh-add-api-for-authorized-keys
See also: https://github.com/NethServer/nethsecurity-ui/pull/102
> Fix SSH error when authorized_keys file is empty

- packages/ns-plug/Makefile
- packages/ns-plug/README.md
- packages/ns-plug/files/30_ns-plug_alerts
- packages/ns-plug/files/health_alarm_notify.conf
- packages/ns-plug/files/mwan.chart.py
- packages/ns-plug/files/netadata_disable_alerts
- packages/ns-plug/files/netadata_enable_alerts
Card: https://trello.com/c/j23JiwwU/183-alerts
Alert handling:
- netdata manages system alerts, including those from multiwan monitoring
- alerts are initially disabled and require a valid subscription for activation
- active alerts are sent to a remote server and logged in `/var/log/messages`
- specific alerts for disk space occupation and WAN down events are transmitted to the remote system.
- clear commands are sent to the remote server upon alert resolution.
mwan3 netdata plugin:
- the file `/usr/lib/netdata/python.d/mwan.chart.py` implements a netdata plugin for mwan3
- the plugin monitors the score of each WAN through the mwan3track status directory
- an alert is triggered when a WAN's score reaches 1
- the minimum mwan3track score is 0, mapped to 1 in netdata for chart plotting …
> Basic alert implementation

- packages/ns-api/README.md
- packages/ns-api/files/ns.ipsectunnel
- packages/ns-api/files/ns.ovpnrw
- packages/ns-api/files/ns.ovpntunnel
- packages/ns-openvpn/Makefile
- packages/ns-openvpn/README.md
- packages/ns-openvpn/files/ns-openvpnrw-add
- packages/ns-openvpn/files/ns-openvpnrw-print-2fa
- packages/ns-openvpn/files/ns-openvpnrw-print-pem
- packages/ns-openvpn/files/ns-openvpnrw-regenerate
- packages/ns-openvpn/files/ns-openvpnrw-revoke
- packages/ns-openvpn/files/ns-openvpnrw-setup
- packages/ns-openvpn/files/openvpn-otp-auth
- packages/python3-nethsec/Makefile
Card: https://trello.com/c/uJW5AAwp/178-openvpn-rw
Changes:
- move common code inside python3-nethsec lib
TODO:
> OpenVPN RW

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.account
- packages/ns-api/files/ns.users
- packages/ns-api/files/ns.users.json
- packages/ns-dpi/files/dpi-config
- packages/ns-objects/Makefile
- packages/ns-objects/README.md
- packages/ns-objects/files/users
- packages/ns-openvpn/README.md
- packages/python3-nethsec/Makefile
User databases can be integrated with OpenVPN and, in the future, with Wireguard. 
Card: https://trello.com/c/uJW5AAwp/178-openvpn-rw
See also: https://github.com/NethServer/python3-nethsec/pull/23
TODO:
> User databases

- packages/ns-api/files/ns.dedalo
- packages/ns-api/files/templates
Changes:
- use only one UAM rule
- remove unused UCI network interface
> ns-api: ns.dedalo, simplify firewall config

- packages/ns-api/files/ns.devices
- Automatically add IPv6 firewall rules when configuring an IPv6 interface
- Allow configuration of a device assigning an IPv6 address and no IPv4 address
> ns-api: ns.devices, add ipv6 firewall rules

- packages/ns-api/files/ns.dashboard
Ensure proper functioning of name resolution.
This modification aims to enhance configuration troubleshooting, especially when users configure a static IP address on a WAN without setting the upstream DNS server.
Card: https://trello.com/c/PLAokNmT/239-default-dns-server
> ns-api: dashboard, better internet check

- packages/ns-api/files/ns.devices
- packages/ns-api/files/ns.ovpnrw
Changes:
- when a server instance is removed, remove also the OpenVPN configuration for the associated users https://trello.com/c/QcHSZwhd/256-openvpn-rw-accounts-previously-removed-reappear-during-new-server-creation
- Avoid to keep half-configured things if the server instance is not created from the drawer. https://trello.com/c/GQjEHIVQ/258-openvpn-rw-reverting-after-deleting-rw-server-breaks-openvpn-rw-page
- commit instance deletion https://trello.com/c/GQjEHIVQ/258-openvpn-rw-reverting-after-deleting-rw-server-breaks-openvpn-rw-page
> OpenVPN RW: multiple fixes

- packages/ns-api/README.md
- packages/ns-api/files/ns.storage
- packages/ns-storage/Makefile
- packages/ns-storage/README.md
- packages/ns-storage/files/add-storage
- packages/ns-storage/files/ns-storage-has-free-space
- packages/ns-storage/files/ns-storage-setup-disk
- packages/ns-storage/files/ns-storage-setup-partition
- packages/ns-storage/files/remove-storage
The package can now save data inside a partition
on the main disk.
Changes:
- the add-storage script now only setups the system
- disk initialization moved to ns-storage-setup-disk script
- added ns-storage-setup-partition script, it must be used only if ns-storage-has-free space exists with 0 code
Card: https://trello.com/c/Avg9egU1/251-log-on-a-dedicated-partition
See UI PR: https://github.com/NethServer/nethsecurity-ui/pull/135
> ns-storage: support partition configuration

- packages/ns-api/files/ns.ovpnrw
Cards:
- https://trello.com/c/dcm4MTHt/270-openvpn-rw-udp-port-not-opened
- https://trello.com/c/vLpFKNll/241-openvpn-configuration-file-not-removed
Other changes:
- remove tun device from LAN zone
- remove interface object: set tun device directly inside VPN zone
> OpenVPN Road Warrior: multiple fixes

- packages/ns-api/files/ns.ovpnrw
- packages/ns-migration/files/scripts/openvpn
- packages/ns-openvpn/files/01-check-status
- packages/ns-openvpn/files/openvpn-otp-auth
Refactor migration after user implementation changes.
Card: https://trello.com/c/qdinj3zr/242-openvpn-migration-refactor
See also https://github.com/NethServer/nethserver-firewall-migration/pull/26
Tests:
> OpenVPN RW: refactor migration

- packages/ns-api/files/ns.dns
- packages/ns-migration/files/scripts/dns
Setting the "local server" to this new value can lead to an unwanted behaviour especially when there are internal resolvers for specific domains
Card: https://trello.com/c/79bj4dW5/275-dns-change-behaviour-of-dns-domain-option
> DNS: do not set local option

- packages/ns-api/Makefile
- packages/ns-api/files/ns.reverseproxy
This changes should close [this card](https://trello.com/c/pwKHHv4d/281-reverseproxy-unable-to-select-default-certificate-for-proxy-pass) for good
> ns-api: fixed issue with certificate assignment in reverse proxy domains

- packages/ns-api/files/ns.dhcp
Dnsmasq DHCP options use the option:<option_name> syntax.
> Fix dhcp option

- packages/ns-api/Makefile
- packages/ns-api/files/ns.reverseproxy
This PR addresses the following:
- resolves an issue where if you delete an ACME certificate and you create it again it would've been set to `pending` state indefinetly
- starts acme service automatically on request certificate and delete
- changes default email to `no-reply@nethsecurity.org` if it hasn't been changed from default
- fixed an issue where updating the destination of a domain wouldn't apply the changes
- added getter and setter for proxy-pass, now list, create and edit from UI should work fine
- added websocket support for all locations created
- added X-Forwarded-Proto, X-Forwarded-For and X-Real-IP to proxies
- added Host header where needed
> Reverse proxy fixes

- packages/ns-api/files/ns.devices
Avoid errors like:
```
pppd[16354]: No response to 5 echo-requests
pppd[16354]: Serial link appears to be disconnected.
```
> ns-api: devices, set pppoe keepalive

- packages/ns-migration/files/scripts/wan
Removes everything set up by the migration process, turning exported file into a mwan using python3-nethsec functions.
Currently not working:
- [rule creation](https://github.com/NethServer/nethsecurity/pull/298/files#diff-e9d19b255f7ff8b7a33335ccfb207afe5706c989027d9a776e1a5980281d9948L98)
> ns-migration: using library functions to create mwans

- packages/ns-storage/files/ns-storage-setup-partition
ns-storage-setup-partition fails if the disk has a "corrupt" GPT table.
```
Warning: Not all of the space available to /dev/sda appears to be used, you can fix the GPT to use all of the space (an extra 61885583 blocks) or continue with the current setting? 
Fixing, due to --fix
```
> ns-storage: discard warnings

- docs/design.md
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.commit
- packages/ns-api/files/ns.commit.json
- run
This api will take care to commit all changes.
API workflow:
- pre-commit hook: run all executable scripts inside the /usr/libexec/ns-api/pre-commit directory
- commit UCI changes
- post-commit hook: run all executable scripts inside the /usr/libexec/ns-api/post-commit directory
- inform ubus about changes to apply them
Each script inside the hook directory will receive the list of changes inside a JSON in the standard input.
Example of pre-commit script, `/usr/libexec/ns-api/post-commit/log`:
```
#!/bin/bash
read -r data
logger -t DEBUG $data
```
Related UI PR: https://github.com/NethServer/nethsecurity-ui/pull/156
TODO:
> ns-api: add ns.commit API

- packages/ns-api/files/ns.devices
Set `ipv6 = auto` on PPPoE interfaces with IPv6 enabled
Card: https://trello.com/c/PYrd3n37/301-interfaces-pppoe-ipv6
See also:
- https://github.com/NethServer/nethsecurity-ui/pull/165
> fix: ipv6 flag management for pppoe ifaces

- packages/ns-api/files/ns.dedalo
Address the following issues:
- when a hotspot relies on a VLAN, its registration fails to capture the MAC address in the Dedalo API's unit section.
- once a hotspot associated with a VLAN is unregistered, the VLAN remains stuck in the interface list and cannot be deleted.
Card: https://trello.com/c/hLhHR4F0/278-hotspot-vlan-management
> ns-api: dedalo, handle vlan device

- packages/ns-api/files/ns.devices
Support for reconfiguration and removal of interfaces configured on a deleted zone.
Card:
- https://trello.com/c/SAG4TmDP/304-interface-with-deleted-zone-is-blocked
See:
- https://github.com/NethServer/nethsecurity-ui/pull/170
> ns-api: ns.devices, fix ifaces on deleted zones

- packages/ns-api/Makefile
- packages/ns-api/files/pre-commit/fix-redirect-reflections.py
If a port forward has a reflection on a non-existing zone, the rule is disabled.
This commit removes all non-existing zones from port forwards.
Card: https://trello.com/c/t7JkwqRz/302-hairpin-nat-issue-with-port-forwarding
> ns-api: pre-commit, fix pf with reflections

- packages/ns-api/files/ns.redirects
Remove "all" from the list of protocols supported by port forward.
On the UI multiple protocols can be selected; e.g. "all" + "udp" doesn't make sense
> ns-api: ns.redirects, remove 'all' protocol

- files/etc/config/firewall
- packages/ns-ui/files/config
Changes:
- expose the UI on port 9090 to ease migration from NS7
- open port 9090 from WAN
- rename UI rule to a more generic HTTP: the rule is used also for proxypass
Card: https://trello.com/c/AotUwjir/317-new-ui-port
> config: enable UI on port 9090 by default

- packages/ns-api/README.md
- packages/ns-api/files/ns.threatshield
Changes:
- show the Enterprise lists only if the machine has an Enterprise subscription and a valid entitlement for the threat shield service
- the entitlement check is done with a remote HTTP call, the result is cached for one hour to increase performance and avoid load on the remote server
- remove the 'warning' blocklist type: it's not possible anymore
Card: https://trello.com/c/UbzjFAwP/314-threat-shield-ip-minimal-ui
> ns-api: threatshield, add entitlement check

- packages/ns-api/files/ns.dhcp
Exclue bond device, but expose bond associated interface
Card: https://trello.com/c/ni6YH2kq/240-interfaces-and-devices-bond
> ns-api: dhcp, exclude bond device

- packages/ns-api/files/ns.devices
- Added specific call to allow deletion of bonds (separating a little the app concerns)
- The bonding is... very complicated, especially on how we manage the behaviour of several things. Here's a list of what changed:
- Removed the check to retrieve the stats only for the visible devices
- Fixed an issue when listing slaves due to the way bonds are recognized
- If there's a device created from a bond interface, you'll find the bond details inside the device, removing entirely the interface from the request. (bond reference can still be found in `bond_interface`)
- When removing interface configuration, I'll remove the device even if it's a bond
> refactor: bond creation process

- packages/ns-migration/files/scripts/network
The UI requires a non-empty dest_ip field
Card: https://trello.com/c/tavYHA5b/283-nat-rules-source-and-destination-netmap
> ns-migration: network, set dest_ip for SNAT

- packages/ns-api/README.md
The example was wrong.
Card: https://trello.com/c/aSCKhOGD/332-netmap-ui
> ns-api: readme, fix netmap example

- packages/ns-api/files/ns.reverseproxy
The main certificate and the chain file must be
separated by a new line, otherwise the generated
file is not in valid PEM format
Card: https://trello.com/c/a8hMaMCD/337-certificate-subject-display-error-on-certificates-page
> ns-api: reverseproxy, fix chain upload

- packages/ns-api/files/ns.reverseproxy
When the option is set to 'self-signed', the nginx init script will try to create a new certificate if the expiration date is less then 13 months
See https://github.com/openwrt/packages/issues/12022
Card: https://trello.com/c/Gps2BetF/336-custom-certificate-overwritten-with-self-generated-certificate-in-openwrt
> ns-api: reverseproxy, force uci_manage_ssl option

- packages/ns-api/files/ns.ovpntunnel
Sometimes connected client has a specific name
and not a generic 'client' label
The change can now handle both cases.
Card: https://trello.com/c/gbHDm9C1/335-openvpn-tunnel-server-status-inconsistency
> ns-api: ovpntunnel, fix server status

- packages/ns-api-server/Makefile
- packages/ns-api-server/files/ns-api-server.initd
The build was failing form ARM targets because the binary is created in a different directory.
Also, with current implementation the nethsecurity-api binary was duplicated inside the package.
> ns-api-server: remove /usr/sbin directory

- files/etc/uci-defaults/99-nethsec-nginx
Do not listen on port 80 to avoid conflict with acme.sh
Card: https://trello.com/c/94ZKwwjY/339-acmesh-lets-encrypt-certificate-request-failed
> uci-defaults: nginx, delete _redirect2ssl

- packages/ns-storage/files/remove-storage
If the partition is still present, the user
will not be able to reuse the free space on later time.
Card: https://trello.com/c/RTeT9qNf/358-storage-cant-reuse-partition-after-deletion
> remove-storage: remove partition

- packages/ns-api/Makefile
- packages/ns-api/files/ns.dhcp
The UI uses the list-active-lease API to show only dynamic leases and not all active ones.
Card: https://trello.com/c/OL753h0v/360-dhcp-static-dymanic-lease
> ns-api: dhcp, hide static leases from active ones

- packages/ns-api/files/schedule-automatic-updates
Fixes:
* Mar  9 16:48:00 NethSec crond[3694]: user root: parse error at sleep
* Every add action adds a crontab line
> ns-api: fix auto-updates cron

- packages/ns-plug/files/send-backup
Acme new version no longer updates http.header every day: the hack to avoid the daily backup is not necessary anymore.
> ns-plug: remove hack for acme backup

- config/sftp-server.conf
Simplify SFTP file transfer with firewall
This commit adds the 'sftp-server' package, eliminating the need for the '-O' flag in scp commands when transferring files with recent SSH client
> conf: add sftp-server package

- packages/ns-migration/files/scripts/wan
Use integer comparison when sorting providers.
This ensure always correct order.
https://trello.com/c/LSlI2cpA/371-migrationmultiwan-wrong-metrics-when-in-backup
> ns-migration: mwan, fix provider sorting

- packages/ns-api/files/ns.migration
Show inside the UI the bond slaves and the bridge ports. Without this change, it was not possible to correctly migrate these logical interfaces from the UI.
The export archive now must contain the 'devices' node inside network.json file
Card: https://trello.com/c/DREXWyEM/377-migration-remapping-should-display-only-physical-devices
Export with: nethserver-firewall-migration-0.0.12-1.ns7.noarch.rpm
> ns-api: migration, expose bridges and bonds

- packages/ns-api/files/ns.devices
Before this change, a vlan device named brX.Y was recognized as a bridge
As consequence the API was failing while trying to access non existing 'ports' field
Card: https://trello.com/c/VaDMVacB/381-interfaces-and-devices-error-when-creating-vlan-over-a-bridge
> ns-api: devices, fix vlan list

- packages/ns-api/files/ns.dhcp
- packages/ns-api/files/ns.migration
- packages/ns-migration/files/scripts/network
Changes:
- refactor alias alias format to match the one required by the UI
- create the device records for the ethernet interfaces: this is also required by the UI
- refactor bond format to match the one required by the UI
- show inside the UI the bond slaves and the bridge ports
The export archive now must contain the 'devices' node inside network.json file
Minimum release of exporter: nethserver-firewall-migration-0.0.12-1.ns7.noarch.rpm
Card: https://trello.com/c/Xxqd9mFS/372-migration-alias-ips
Card: https://trello.com/c/DREXWyEM/377-migration-remapping-should-display-only-physical-devices
> ns-migration: network, fix alias

- packages/ns-api/files/ns.ipsectunnel
The tunlink interface option must be set to the wan interface the tunnel is configured on.
Card: https://trello.com/c/mFdihKrk/349-ipsec-tunlink-set-to-wan
> ns-api: ipsec, set wan interface

- packages/ns-flashstart/files/flashstart-auth
Fix wrong field : needs to look in the db for "username", not "user"
> Fix flashstart-authentication : bad "user"

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.controller
- packages/ns-api/files/ns.controller.json
- packages/ns-api/files/ns.plug
Changes:
- add a new ns.controller API that can be called from the controller to retrieve and cache unit info
- ns.plug API: fix unit_name set and do not delete rpcd user (more info inside commit messages)
See also https://github.com/NethServer/nethsecurity-controller/pull/16
> Controller: new API and improve ns-plug

- packages/ns-api/files/ns.factoryreset
After a factory reset the storage partition can't be accessed from the UI.
To workaround the problem, the user must access the command line and manually remove the partition or add it back with the `add-storage` command.
This commits forces the removal of the partition.
Caveats:
- if the remove-storage command fails (this is unlikely to happen), the partition could be still in a dangling state
- the partition removal works only if the factory reset is performed using the APIs
> ns-api: factoryreset, remove storage partition

- packages/ns-api/files/ns.ovpnrw
The API was trying to create twice the same user
Card: https://trello.com/c/OPPxiQZK/403-openvpnrwunable-to-create-account-from-users-during-server-creation
> ns-api: ovpnrw, fix user import with remote db

- packages/ns-api/files/ns.flashstart
On a clean machine the 'server' could be empty.
Avoid error:
```
Traceback (most recent call last):
File "/usr/libexec/rpcd/ns.flashstart", line 62, in <module>
e_uci.get('dhcp', dnsmasq, 'server', list=True))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/euci/__init__.py", line 85, in get
```
Issue #411
> ns-api: flashstart, fix config on clean machine

- packages/ns-api/files/ns.flashstart
- packages/ns-flashstart/files/flashstart-setup-firewall
Changes:
- fix redirect rules
- force dnsmasq restart
See:
- #420 
- #422
> ns-flashstart: fix firewall rules

- packages/ns-api/Makefile
- packages/ns-api/files/post-commit/reload-ipsets.py
The 'fw4 reload' command does not update ipsets if an element has been removed.
The new post-commit hook forces the reload of all ipsets if an ipset has been changed during last uci commit.
Please note that the reload may take a while before been effective, usually 3-4 seconds on a fast machine.
#423
> ns-api: force ipset reload

- packages/ns-api/files/ns.ovpnrw
If the user already exists inside the db, do not recreate it to avoid errors.
#437
> ns-api: ovpnrw, fix remote user creation

- files/etc/uci-defaults/99-nethsec-rpcd-timeout
Make sure default rpcd timeout is at 300 seconds
to avoid errors on long tasks.
If the timeout has been already modified, preserve the value.
> uci-defaults: set rpcd timeout

- packages/ns-api/files/ns.ovpnrw
- packages/ns-migration/files/scripts/openvpn
Changes:
- Make sure the tap device is added to the bridge; also remove it on edit
- Avoid tap interface name collision, if multiple bridged servers has been configured.
Todo:
#445
> OpenVPN: fix bridged road warrior server

- packages/ns-api/files/ns.dhcp
The force option is enabled by default for new DHCP servers: this should avoid problems during migration and installation on existing networks.
#454
> ns-api: dhcp, force option enabled by default

- packages/ns-threat_shield/files/ts-ip
When the machine is unregistered, the premium lists are not accessible anymore.
#471
> ns-threat_shield: remove premium lists on unregister

- packages/ns-plug/files/register
The command was accessing a non-existing path:
https://my.nethesis.it/api//system/info instead of https://my.nethesis.it/api/system/info.
Change on the enterprise path is just cosmetic.
#491
> ns-plug: fix register for community subscription

- packages/ns-migration/files/scripts/network
Make sure interface name does not exceed 15 chars.
#493
> ns-migration: truncate interface name

- packages/ns-threat_shield/files/banip.nethesis.feeds
The previous regexp gives the following error:
gawk: cmd. line:1: warning: regexp escape sequence `\d' is not a known regexp operator
and the feed is ignored:
May  3 17:09:47 fw banIP-0.9.4-3[16535]: skip empty feed 'yoroisusplvl2v4'
> ts-ip: fix gawk regexp

- packages/ns-dpi/files/70dpi
Make sure configuration files exist because they are parsed from the dpi API
#473
> ns-dpi: restore community signatures

- packages/ns-api/files/ns.scan
Display only the content from the arpscan.
As per Davide F. request
Private discussion: https://mattermost.nethesis.it/nethesis/pl/hc913pjqc3nd8gntweiw49qnoc
> ns-api: scan, remove /proc/net/arp content

- packages/ns-storage/files/ns-storage-has-free-space
- packages/ns-storage/files/ns-storage-setup-partition
If there is a free space before the first partition, just ignore it. Use always the free space at the end of the disk.
Example of a disk with free space before the first partition:
```
Number  Start   End     Size    File system  Name  Flags
17.4kB  262kB   245kB   Free Space
1      262kB   17.0MB  16.8MB  fat16              legacy_boot
2      17.0MB  332MB   315MB
332MB   64.0GB  63.7GB  Free Space
```
Workaround for #492
> ns-storage: fix management of free partition

- packages/ns-threat_shield/Makefile
- packages/ns-threat_shield/files/adjust-banip.py
Create a post-commit hook that adjusts the status of banip service. Previously, if banip was not running, the UI was not able to enable it.
#507
> ns-threat_shield: force banip start on post-commit

- packages/ns-threat_shield/Makefile
- packages/ns-threat_shield/files/configure-banip-wans.py
New pre-commit hook that configures all banip wan options. The hook is executed every time network or banip databases have been changed.
#505
> ns-threat_shield: configure banip wans

- packages/ns-api/files/ns.devices
Show OpenVPN server/client tunnels in `ns.devices list-devices`
> ns-api: ns.devices, fix ovpn devices listing

- packages/ns-threat_shield/files/adjust-banip.py
When changing ban_ifv4, ban_ifv6, ban_dev and ban_trigger options, after the banip database commit, the nft rules are not updated.
This change is an hack to force the restart of banip. A simple "/etc/init.d/banip restart" is not enough, because sometimes the service does only a reload which does not recreate nft rules
#505
> ns-threat_shield: force banip restart

- packages/ns-api/files/ns.threatshield
Make sure to set the options that are usually controlled by 'autodetect' which is now disabled.
#505
> ns-api: banip, set missing options

- packages/ns-storage/files/ns-storage-has-free-space
- packages/ns-storage/files/ns-storage-setup-partition
- packages/ns-storage/files/remove-storage
On a EFI machine the partition can't be managed because /boot is not loaded.
#529
> ns-storage: fix partition on EFI

- packages/ns-api/README.md
- packages/ns-api/files/ns.dashboard
The check returns "warning" if:
- there is at least one WAN interface configured with static IP
- dnsmasq has no configured upstream servers
> ns-api: dashboard, add service dns-check-configured

- packages/ns-phonehome/files/phonehome
The `distro` node is required, otherwise the server will not accept the payload.
Regression introduced in commit 2b9e1d1251924562d90ec8a8514b70d816519f05
Server error:
```
n1 app[1492815]: [2024-05-16 12:49:38] production.DEBUG: JsonSchema validation failed {"/facts":["The required properties (distro) are missing"]}
```
> ns-phonehome: fix json format

- packages/ns-phonehome/files/phonehome
- packages/ns-plug/files/inventory
Changes:
- add usage stats to phonehome
- add usage stats to inventory
Inventory example:
```json
{"arp_macs": "3", "dmi": {"product": {"name": "Standard PC (Q35 + ICH9, 2009)", "uuid": "3a278260-9b70-4dcc-836c-032e2d31ca57"}, "bios": {"version": "1.16.2-1.fc38", "vendor": "SeaBIOS"}, "board": {"product": "qemu-standard-pc-q35-ich9-2009", "manufacturer": "QEMU"}}, "virtual": "KVM", "kernel": "Linux", "kernelrelease": "5.15.150", "networking": {"fqdn": "NethSec"}, "os": {"type": "nethsecurity", "name": "NethSec", "release": {"full": "8-23.05.3-ns.0.0.5-rc2-62-ge22c143", "major": 7}, "family": "OpenWRT"}, "processors": {"count": "2", "models": ["Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz"], "isa": "x86_64"}, "timezone": "UTC", "system_uptime": {"seconds": "24768"}, "esmithdb": {"networks": …
```
> Improve usage statistics

- packages/ns-api/files/ns.ovpnrw
When OTP authentication is enabled, the server should not request the password again after one hour.
#538
> ns-api: ovpnrw, disable reneg-sec for OTP

- packages/ns-api/files/ns.threatshield
Make sure to set ban_nftexpiry and ban_logcount to avoid banning indefinitely hosts with bad login attempts.
> ns-api: threatshield, set ban_nftexpiry and ban_logcount

- config/nat_helpers.conf
- config/sipalg.conf
- docs/design/nat_helpers.md
- packages/ns-api/Makefile
- packages/ns-api/files/load-kernel-modules
- packages/ns-api/files/load-modules
- packages/ns-api/files/nat-helpers.keep
- packages/ns-migration/Makefile
- packages/ns-migration/files/scripts/nat_helpers
Needed to allow active ftp sessions
Note: windows FTP client only uses active FTP
https://github.com/NethServer/nethsecurity/issues/544
> config: add nat helpers

- packages/ns-phonehome/Makefile
- packages/ns-phonehome/files/phonehome
~~Opened now the latest version, it appears that the version is uncorrectly stripped out of endline and quotes (from /etc/os-release)~~
~~This fix works with both latest versions and testing ones~~
Removed version definition in facts, for Nethsecurity expecting to use version inside distro object.
> ns-phonehome: removing version from facts

- .github/workflows/release-stable.yml
Adding trigger sync between dev packages and stable ones.
If you have any question regarding `rclone` config, turns out that `rclone` [is a very neat piece of software](https://rclone.org/docs/#config-file).
> ci: adding rclone sync between dev and release

- packages/ns-api/files/ns.ovpnrw
Avoid error if the date is invalid or the certificate file name contains spaces
#553
> ns-api: ovpnrw, better handle cert expirtation

- packages/ns-api/files/ns.ipsectunnel
- packages/python3-nethsec/Makefile
Make sure at least a wan is returned.
Before this commit, the function could also return a None value. In that case, the IPsec tunnel can connects but the traffic does not flow because there is no ipsecX interface.
#571
> ipsec: fix wan interface retrieval

- packages/ns-api/files/ns.backup
This pull request fixes the validation message to  `passphrase`. This PR updates the code to correctly handle the validation and provides a more informative error message inside the UI
REFs:
- https://github.com/NethServer/nethsecurity-ui/pull/295
- #587
> Fix validation error in ns-api code

- packages/ns-migration/files/scripts/dhcp
This pull request updates the `dhcp` script to set the `dhcpleasemax` option only when the value is greater than 1000. This ensures that the default value of 1000 leases is used when the value is lower.
https://github.com/NethServer/nethsecurity/issues/585
> Set dhcpleasemax when greater than 1000

- files/usr/bin/ns-download
Fixing issue where with subscription enabled wasn't possible to download the correct image (and hence updating the firewall completely)
Ref: #412
> core: fix ns-download due to current subscription changes

- packages/ns-api/files/ns.backup
This pull request fixes a validation error in the `registered-restore` function of the `ns.backup` file.
The error occurred when a passphrase was not provided. The fix updates the error message to specifically indicate that a passphrase is required.
#587
> Fix validation error in registered-restore

- packages/ns-dpi/files/dpi-update
Support DPI signatures download both for enterprise and community subscriptions.
Issue #603
> ns-dpi: download signatures from new URL

- packages/ns-migration/files/scripts/wan
Make sure mwan3 is disabled if the original machine has no provider configured.
#613
> ns-migration: mwan, disable when there are no providers

- files/etc/uci-defaults/99-nethsec-remove-scheduled-upgrade
Removing the scheduled update once ran, removing the cron from the system.
Ref:
- https://github.com/NethServer/nethsecurity/issues/610
> fix: removing scheduled update once ran

- packages/ns-api/files/ns.ovpnrw
On instances migrated from NS7, the CN can be in the form <user>@<domain>. The fix add some logic to handle this special case.
#631
> ns-api: ovpnrw, fix status check for migrated

- packages/ns-threat_shield/files/nethesis-dns.sources
- packages/ns-threat_shield/files/ts-dns
A community subscription can now access enterprise blocklists if it has a valid entitlement for the service.
Remote validation now differs based on subscription type.
> ns-threat_shield: use new enterprise download URL

- packages/ns-threat_shield/files/banip.nethesis.feeds
- packages/ns-threat_shield/files/ts-ip
A community subscription can now access enterprise blocklists if it has a valid entitlement for the service.
Remote validation now differs based on subscription type.
> ns-threat_shield: IP, use new enterprise download URL

- packages/ns-api/README.md
- packages/ns-api/files/ns.threatshield
- packages/ns-threat_shield/Makefile
- packages/ns-threat_shield/README.md
- packages/ns-threat_shield/files/community-dns.sources
- packages/ns-threat_shield/files/nethesis-dns.sources
- packages/ns-threat_shield/files/ts-dns
Improved threat shield implementation for community.
To better understand how threat shield DNS works, see [README](https://github.com/NethServer/nethsecurity/blob/021fa95ce170c804636d89608aa0f44b6df4c765/packages/ns-threat_shield/README.md#ts-dns)
APIs are suitable for a future implementation of the UI very similar to one already implemented for Threat Shield IP.
Issue #640 
See also: 
- https://github.com/NethServer/nethsecurity-docs/pull/100
- https://github.com/nethesis/blacklists/pull/23
> ns-threat_shield: add community lists

- packages/python3-nethsec/Makefile
Pulling in the changes coming from `python3-nethsec`
Ref:
- #646
> python3-nethsec: bump to 0.0.70

- packages/ns-flashstart/files/flashstart-apply
Reduce number of queries for the root DNS server:
these queries are billed by FlashStart
#657
> ns-flashstart: use lazy health check mode

- packages/ns-api/files/ns.reverseproxy
Fixes issue where it's not possible to delete certificates with same domain requested if they're used in the reverse proxy
Ref: #643
> ns-api(reverse-proxy): fixing duplicate acme domain requests

- docs/design/distfeed.md
- packages/ns-api/files/ns.update
- packages/ns-api/files/schedule-automatic-updates
- packages/ns-plug/Makefile
- packages/ns-plug/files/40_ns-plug_automatic_updates
- packages/ns-plug/files/update-packages
Add a new `update-packages` script, features:
- all operations are written to syslog and stderr: this change is very useful for troubleshooting and tracking the automatic updates
- accept the 'force-stable' flag to gather updates from stable channel regardless of subscription status: this can be used to quickly distribute fixes
#668
> New update-packages script

- packages/ns-openvpn/files/10-static-lease
Migrated account has the CN in the form <user>@>domain>. Remove the domain part to search for an IP reservation.
The fix is similar to ead59c8db47b1a3b8c761f97f7f539d32cb956a1
#683
> ns-ovpn: handle reservation for migrated account

- packages/ns-api/files/ns.ssh
The API does not generate a valid JSON output, still it works correctly with rpcd.
The fix is usefull when invoking the script without rpcd as wrapper
> ns-api: ssh, fix JSON output

- packages/ns-openvpn/Makefile
The used file has been renamed.
Also, uci defaults inside the postinst script do not work. Cleanup useless code.
> ns-openvpn: remove uci-defaults from postinst

- packages/ns-api/files/ns.objects
This reverts commit 667747139094107f88d25a2bc856c59fbf4ba57b.
The new implementation returns also non-domains objects.
#697 
I think this change can cause a regression in #671
> Revert "ns-api(objects): use new library function to list domains"

- packages/ns-api/files/ns.redirects
`ns.redirect list-object-suggestions` api should return domain sets only. Before this change also other objects, e.g. VPN users and DHCP reservations were returned.
Ref:
- https://github.com/NethServer/nethsecurity/issues/689
> fix: ns.redirect list-object-suggestions

- packages/ns-api/files/ns.mwan
- packages/python3-nethsec/Makefile
It appears that CIDR and IPSets were left out from MWAN rule configuration
Needs:
- https://github.com/NethServer/python3-nethsec/pull/63
> ns-api(mwan): adding CIDR and IPSets to SRC and DST

- packages/ns-api/files/ns.mwan
- packages/ns-objects/README.md
- packages/python3-nethsec/Makefile
Changes:
- remove domain sets, mwan ipset support is broken on 23.05
- remove IPv6 objects, mwan does not directly support IPv6
Fixes failed tests: 3, 4 and 5
References:
- Issue #671
- Requires: https://github.com/NethServer/python3-nethsec/pull/64
> mwan: remove unsupported objects

- packages/ns-api/files/ns.backup
- packages/ns-plug/files/send-backup
This will ease the restore of packages installed
from repositories after an image upgrade
Please note that the package list is already saved during the upgrade process, if executed from the UI.
Example of restore:
```
grep -E '\w+\s+overlay$' /etc/backup/installed_packages.txt | awk '{print $1}' | xargs opkg install
```
References:
- #711 
- #710
> ns-api & ns-plug: add package list to backup

- files/etc/uci-defaults/95-nethsec-migrate
- packages/ns-migration/README.md
- packages/ns-migration/files/ns-import
- packages/ns-migration/files/scripts/network
- Fix issue #716 
- Always log migration to /root/migration.log
See each commit message for more details
> Migration: fix failure and improve logging

- packages/ns-don/files/20-don.nft
Add access to port 19999 from tunDON to allow viewing netdata UI from remote support sessions.
> ns-don: open netdata port (19999)

- packages/ns-api/files/ns.reverseproxy
The allow field is valid only inside location records.
> ns-api: reverseproxy, fix allow field

- docs/design/nat_helpers.md
- packages/ns-api/README.md
- packages/ns-api/files/load-kernel-modules
- packages/ns-api/files/ns.nathelpers
- packages/ns-api/files/ns.nathelpers.json
Ref:
- https://github.com/NethServer/nethsecurity/issues/724
> ns-api: add nathelpers api

- packages/ns-api/files/ns.plug
- packages/ns-plug/files/ns-plug
Make sure to send the logs using FQDN to controller: this will prevent conflicts with firewall with the same hostname
#733
> ns-api & ns-plug: enable/disable FQDN in logs

- packages/ns-api/files/ns.ovpnrw
- packages/ns-openvpn/Makefile
- packages/ns-openvpn/files/99_ns-openvpn-renew-crl
- packages/ns-openvpn/files/ns-openvpnrw-extend-crl
- packages/ns-openvpn/files/ns-openvpnrw-init-pki
Extending CRL expiration when generating the CRL file, also extending the time when updating the package or the whole image
Ref:
- https://github.com/NethServer/nethsecurity/issues/739
> Extend OpenVPN CRL expiration

- packages/ns-api/files/ns.ovpntunnel
> ns-api: assigning a dev_type so that UI does not rely on defaults

- docs/design/distfeed.md
- packages/ns-plug/files/update-packages
When the --force-stable flag, there might be an issue if
metadata have been previously downloaded using the subscription
repository: opkg will try to download some packages using
the subscription URL instead of the sable one.
This PR removes the force flag and restore the old documentation.
#765
> Fix update packages

- packages/ns-migration/files/scripts/acme
Avoid error like:
```
Sep 23 00:00:00 sole acme: account_email option is required
```
#773
> ns-migration: acme, set account_email

- packages/ns-migration/files/scripts/routes
Such routes could be created from the old Server Manager, but not from Cockpit.
#778
> ns-migration: import routes without device

- packages/ns-api/files/ns.dashboard
Modify the grep command to include events from the current hour until now. This ensures that recent threat
shield events are not missed in the dashboard counter.
#781
> ns-api: improve threat_shield_ip count accuracy

- packages/ns-api/README.md
- packages/ns-api/files/ns.talkers
- packages/python3-nethsec/Makefile
Add to the realtime monitoring api the applications and protocols most active:
This is intended as a breaking change, and `ns-api` should be released as `2.0.0`
Ref:
- https://github.com/NethServer/nethsecurity/issues/756
> Realtime monitoring: instant ranking

- packages/ns-api/README.md
- packages/ns-api/files/ns.ovpnrw
Make a ns-api wrapper to create a bundle of all certficates  in an archive 
Refs: https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=80692610
```
root@NethSec:~# echo '{"instance": "ns_roadwarrior1"}'| /usr/libexec/rpcd/ns.ovpnrw call download_all_user_configurations
{"archive_path": "/var/run/ns-api-server/downloads/ns_roadwarrior1_user_configurations.tar.gz"}
```
This will create the archive inside: `/var/run/ns-api-server/download`.
if we untar the archive
```
root@NethSec:~# tar -xvzf /var/run/ns-api-server/downloads/ns_roadwarrior1_user_configurations.tar.gz
helene.ovpn
stephane.ovpn
```
> ns-api: openvpnrw, add download all user configurations

- packages/ns-threat_shield/files/banip-defaults
The icmp limit could be hit if the network, or the firewall itself, is pinging many hosts for WAN status checking or link quality monitor.
> ns-threat_shield: increase default icmp limit

- packages/ns-api/files/ns.netdata
Netdata was restarted before the file descriptor of fping.conf was closed.
On stop, netdata was not able to find the fping process to be killed.
#824
> ns-api: netdata, fix restart

- packages/ns-api/files/ns.redirects
- packages/ns-objects/README.md
The ns_src field can support all object types except for host sets including an IP range
#818
> ns-api: redirects, expand object support

- packages/ns-api-server/files/ns-api-server.initd
This change allows `ns-api-server` to restart without invalidating the current active tokens. A reboot will still empty out the folder invalidating all the tokens provided.
> ns-api-server: using runtime directory to save jwt_secret

- files/usr/sbin/ns-upgrade
Adding this delay helps the UI to receive the response before the unit reboots
> fix: adding delay for response when upgrading image

- packages/ns-report/files/dpireport
Changes:
- restart threads if netifyd socket disappears
- wait for netifyd socket indefinitely
- log socket connection and disconnection to ease debug
#809
> ns-report: fix dpireport crash

- builder/build-builder
- docs/build/index.md
- run
Use special parameters to build an image based on OpenWrt snapshot. Snapshots can be used to test upcoming changes.
How to use:
1. build the image builder based on main branch:
```
pushd builder
OWRT_VERSION=snapshot ./build-builder
popd
```
This will create an image named `ghcr.io/nethserver/nethsecurity-builder:snapshot` than will be used to build the output image
2. build the image using the builder:
```
IMAGE_TAG=snapshot ./run
```
Since multiple versions of OpenWrt can't be build using the same directory, the snaphost build will use 
different podman volume named with `_snapshot` suffix, like `nethsecurity-build_dir_snapshot`
> build: support snapshosts

- packages/ns-api/files/ns.dhcp
Imported DHCP servers do not use the interface name as id, but something like ns_dhcp_X
#855
> ns-api: dhcp, handle migrated configurations

- packages/ns-api/files/ns.qos
For bandwidths below or equal to 1000 Mbps, leave the default behavior. If upload speed > 1000 Mbps, set egress_options to no-split-gso If download speed > 1000 Mbps, set ingress_options to no-split-gso
#845
> ns-api: qos set egress/ingress options

- files/etc/uci-defaults/99-nethsec-pppoe
- packages/ns-api/Makefile
- packages/ns-api/files/ns.devices
- packages/ns-api/files/remove-pppoe-keepalive
The PPPoE connection does not reconnect after a disconnection when the keepalive option is set.
Please note that the change is not applied until a network interface restart is executed.
#843
> Remove keepalive option from PPPoE

- packages/ns-migration/files/scripts/dhcp
Removing `domain` configuration setting
Ref:
- https://github.com/NethServer/nethsecurity/issues/855
> ns-migration: removing domain from dhcp configuration

- files/usr/sbin/ns-log-size
- packages/ns-storage/files/30_ns-storage
This pull request adds a script to adjust manually the size of the log, the service must be restarted after by the sysadmin
```
ns-log-size get
ns-log-size set 104857600
```
verify 
`cat /var/etc/rsyslog.conf`
References:
- https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=81705733
- mattermost talk https://mattermost.nethesis.it/nethesis/pl/sy17gdxa8tr8tj4aptwff4qxfa
- Issue: #865
> Update log rotation size to a dynamic value

- packages/ns-api/files/ns.dashboard
On ARM boards, some devices are not present
See https://community.nethserver.org/t/nethsecurity-install-on-raspberry-pi-4b/24810
> ns-api: fix hardware info for ARM boards

- packages/ns-api/files/post-commit/reload-ipsets.py
Due to a unkown issue, if an ipset is being changed in uci and committed, no changes are triggered in the nft definitions. This is the only way to enforce such change. It appears that the previous `reload-sets` reloads only the files attached to the ipsets definitions.
Refs:
- https://forum.openwrt.org/t/add-ip-to-ipset-in-fw4-do-not-work/160334
- https://github.com/NethServer/nethsecurity/issues/896
> fix(ns-api): restarting fw4 when ipset changes

- packages/ns-api/files/post-commit/reload-ipsets.py
> fix(ns-api): restarting fw4 when updating an ipset

- files/etc/uci-defaults/99-nethsec-nginx
- packages/ns-ui/files/ns-ui
The fix will be available on fresh installations or image upgrades due to the edit of a uci-defaults.
This doesn't apply to nginxs that have the reverse proxy on a different port due to the configuration overwrite.
Ref:
- https://github.com/NethServer/nethsecurity/issues/897
> fix(nginx): using nohostname for logs

- packages/ns-api/files/ns.dashboard
Do not output anything on stderr if some
hosts fail to be resolved.
#945
> fix(ns-api): dashboard, improve internet check

- packages/ns-api/files/post-commit/configure-netifyd.py
- packages/ns-dpi/README.md
Improve the filtering of network interfaces by excluding specified patterns and ensure that internal and external interfaces are unique and sorted in the netifyd configuration.
https://github.com/NethServer/nethsecurity/issues/929
we can remove by the cli some interface (we look by startswith, so `wg` == `wg*`
- how to add an exclusion list 
```
uci add_list netifyd.@netifyd[0].exclude='eth1'
uci add_list netifyd.@netifyd[0].exclude='tun'
uci add_list netifyd.@netifyd[0].exclude='wg'
uci commit netifyd
```
- how to add and remove item of the exclusion list 
```
uci delete netifyd.@netifyd[0].exclude='eth1'
uci add_list netifyd.@netifyd[0].exclude='eth2'
uci commit netifyd
```
- how to remove completely the exclusion list
```
uci delete netifyd.@netifyd[0].exclude
uci commit netifyd
```
> Enhance interface filtering and ensure uniqueness in netifyd configuration

- config/snort3.conf
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.snort
- packages/ns-api/files/ns.snort.json
- packages/ns-api/files/post-commit/restart-cron.py
- packages/snort3/Makefile
- packages/snort3/README.md
- packages/snort3/files/main.uc
- packages/snort3/files/nftables.uc
- packages/snort3/files/ns-snort-rules
- packages/snort3/files/snort-mgr
- packages/snort3/files/snort-rules
- packages/snort3/files/snort.config
- packages/snort3/files/snort.init
- packages/snort3/files/snort.uc
- packages/snort3/patches/100-remove-HAVE_HS_COMPILE_LIT-to-work-around-upstream-b.patch
- packages/snort3/patches/110-packet_capture-Fix-compilation-with-GCC-13.patch
NethSecurity configuration for Snort3:
- new rules download script
- improved init
Features:
- rules: Snort community and Snort subscriber
- bypass: source and destination for IPv4 and IPv6
- automatic configuration in NFQ mode
- automatic configuration for HOME_NET variable including VPN networks
- suppression rules by source and destination
- log alert to syslog
Possible improvements:
- add a description for IPS bypass rules
- add a description for disabled rules
- add an API to add/edit/delete the bypass rules
- add an API to add/edit/delete the suppression rules
Documentation:
-  [README](https://github.com/NethServer/nethsecurity/blob/snort3_giacomo/packages/snort3/README.md) for more info and how to use and configure
- [API …
> Snort3 basic setup

- packages/ns-api/files/ns.ovpnrw
Fix `ns.ovpnrw list-users` API. If the OVPN instance exists but hasn't been configured, return an empty list. Previously, the `list-users`  would throw an exception in this scenario.
Ref:
- https://github.com/NethServer/nethsecurity/issues/943
> fix(ns-api): fix ns.ovpnrw list-users

- packages/ns-api/README.md
- packages/ns-api/files/ns.dpireport
Due to needs of https://github.com/NethServer/nethsecurity-ui/pull/452 the filtering section must be expanded adding protocol and remote host filtering.
Ref:
- https://github.com/NethServer/nethsecurity/issues/938
> feat(dpi): adding more filtering options

- packages/ns-api/files/post-commit/configure-netifyd.py
- packages/ns-dpi/README.md
Revise the exclusion logic in the Netifyd configuration to use `ns_exclude` instead of `exclude`, and update the README to reflect this change.
https://github.com/NethServer/nethsecurity/issues/929
> Update exclusion logic and documentation for Netifyd

- packages/ns-flashstart/files/flashstart-apply
- packages/ns-flashstart/files/flashstart-auth
Ref:
- https://github.com/NethServer/nethsecurity/issues/955
> fix(flashstart): fixed pinging issues

- packages/ns-flashstart/files/flashstart-auth
Changes on the registration script:
- preserve WAN order: make sure that the same id is always associated to the same WAN
- fix registration for PPPoE WANs: previously curl was using the underlying eth interface instead of the ppp one
> fix(ns-flashstart): preserve WAN order

- packages/ns-api/files/ns.dpireport
When showing details of network traffic, do not
display hosts with 0 bytes of traffic
Before:
After:
> fix(ns-api): improve dpireport details

- packages/ns-api/files/ns.storage
This pull request introduces a new function to improve how storage information is retrieved and used in the `ns.storage` module. It also makes sure that the fstab section is always named `ns_data`.
#960
> ns-storage: fix named section after upgrade

- config/speedtest.conf
Add the speedtestcpp package to run speed tests from the command-line.
Note: best server selection seems to fail sometimes, giving non-optimal results.
Try again with `speedtest --force-by-latency-test` to see if a different server is selected.
> feat(conf): add speedtestcpp package

- packages/ns-api/files/ns.snort
- packages/snort3/files/snort.init
Changes:
- setup queue_maxlen as startup parameter
- set as queue_maxlen to 4096 during the first configuration, the value can be changed later manually using uci command line
> Snort: support queue_maxlen

- packages/mwan3/Makefile
- packages/mwan3/files/etc/config/mwan3
- packages/mwan3/files/etc/hotplug.d/iface/15-mwan3
- packages/mwan3/files/etc/hotplug.d/iface/16-mwan3-user
- packages/mwan3/files/etc/init.d/mwan3
- packages/mwan3/files/etc/mwan3.user
- packages/mwan3/files/etc/uci-defaults/mwan3-migrate-flush_conntrack
- packages/mwan3/files/lib/mwan3/common.sh
- packages/mwan3/files/lib/mwan3/mwan3.sh
- packages/mwan3/files/usr/libexec/rpcd/mwan3
- packages/mwan3/files/usr/sbin/mwan3
- packages/mwan3/files/usr/sbin/mwan3rtmon
- packages/mwan3/files/usr/sbin/mwan3track
- packages/mwan3/src/sockopt_wrap.c
> Fork mwan3

- packages/ns-phonehome/files/phonehome
Using `/sys/class/dmi/id/product_uuid` is not a good way to determine unique machines, this is due the possibile deduplication of the same value using VMs and additional issues regarding the non-standard of the value.
Sticking to the random generated value for all firewalls.
> fix(phonehome): get always the generated UUID instead of the system one

- config/ns-binding.conf
- packages/ns-binding/Makefile
- packages/ns-binding/README.md
- packages/ns-binding/files/ns-binding.init
- packages/ns-binding/files/ns-binding.py
Introducing IP/MAC binding for DHCP interfaces.
Ref: https://github.com/NethServer/nethsecurity/issues/918
> feat: adding ns-binding package

- .github/workflows/change-status-on-labels.yml
Add condition to check if the issue is open before running the
`update-project-status` job. This prevents unnecessary operations on
closed issues. Also, refine the condition for setting the new status
to ensure it only runs when a valid status is present.
> fix(workflow): status update only for open issues

- config/debugtools.conf
- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.ovpnrw
- packages/ns-api/files/ns.wireguard
- packages/ns-api/files/ns.wireguard.json
Wireguard configuration from command line interface.
Features:
- support multiple WireGuard server instances
- each instance has its own reserved zone
- all accounts (peers) have a static allocated IP address
- download account configuration as text or qrcode
- net2net mode
- support peer pre-shared key
- if the server instance is linked to a user database, peers will be associated to the existing users
- import a standard wireguard configuration file
Limitations:
- only /24 networks are supported
- the IP of an account can't be changed
Possible improvements:
- use WireGuard account IP address inside firewall objects
- add WireGuard tunnels to the local monitoring 
- add WireGuard tunnels to the remote monitoring
- correctly display WireGuard interfaces under the VPN section inside the …
> WireGuard CLI configuration

- packages/ns-api/Makefile
Updating `ns-api` version due to Monitoring changes, this helps controller to recognise the changes and prompt confirmation for access.
> chore(ns-api): bump minor release

- packages/snort3/README.md
- packages/snort3/files/ns-snort-rules
- Fix download with oinkcode
- Add gid field to the list of ns_disabled_rules (see the readme for the new usage)
> Snort: multiple fixes

- packages/ns-api/Makefile
- packages/ns-api/files/ns.update
If for any reason the upstream update server goes offline (both community and enterprise repositories), several issues arise while viewing the Updates page.
By adding the `python3-requests` package it's possible to figure what is going wrong and what happened to the request, leaving the UI with specific error messages that allows to tell the user exactly what is going on.
> fix(ns-api): gracefully handle error when checking for updates

- packages/ns-plug/files/mwan-hooks
The script uses a bash-only syntax. Using bash gives the following error: /usr/libexec/ns-plug/mwan-hooks: line 17: failed_count++: not found
> ns-plug: mwan3 hooks needs bash

- packages/ns-plug/files/40_ns-plug_mwan_hooks
/etc/mwan3.user should finish in a timely manner.
See https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3#alertsnotifications
As of today, the only script is send-mwan-alert which can take 3 minutes.
https://github.com/NethServer/nethsecurity/issues/1014
> mwan3: run user scripts in backgorund

- packages/ns-api/README.md
- packages/ns-api/files/ns.snort
- packages/snort3/files/ns-snort-rules
- packages/snort3/files/snort.init
Changes:
- Added API to read configuration
- Added API to check oinkcode (this is done by downloading the registered rules, not efficient but the only way)
- Removed `ns_disabled_rules` from `setup` API, this will need a separate API.
- Now service restarts at every change in `snort` config
- Added ability to comment bypasses 
~~NOTE: now the service downloads the new rules at every restart. It's not optimal, but:~~
~~1. checking if the files in `rules` exists, is not a indicator of the need the rules again (I.E. if you are a community user and then add the "oinkcode" later), this locks the user to the old rules until the cronjob applies~~
~~2. there's no way to know what changed in the configuration, this was useful in case we want to re-download the rules and reapply them, only if the …
> feat(snort): adding API for UI

- packages/snort3/files/ns-snort-rules
From https://docs.snort.org/rules/headers/actions
Block: Drop packet, block remainder session 
Drop: Drop packet only
TCP sessions need "block" to stop the connection.
> fix(ips): configuring block instead of drop

- packages/ns-migration/Makefile
- packages/ns-migration/files/scripts/openvpn
Ref:
- https://github.com/NethServer/nethsecurity/issues/1047
> fix(ns-migration): allow activation of 2FA on migrated instances

- packages/ns-plug/files/send-mwan-alert
Running /etc/init.d/mwan3 restart produces a rapid disconnect/connect sequence which triggers an alert lasting a few seconds. This PR avoid the false alarm delaying disconnect alerts by 30 seconds.
https://github.com/NethServer/nethsecurity/pull/992 required.
See #1054
> fix(ns-plug): avoid mwan3 alerts during restart

- packages/ns-api/README.md
- packages/ns-api/files/ns.threatshield
- Restart `adblock` service at the end of the following `ns.threatshield` apis: `dns-add-blocked`,  `dns-edit-blocked`, `dns-add-allowed`,  `dns-edit-allowed`
- Add `dns-list-zones` api
- Prevent `wan` zone in `dns-edit-settings`
Ref:
- https://github.com/NethServer/nethsecurity/issues/906
> fix(ns-api): fix threat shield dns apis

- packages/ns-migration/files/scripts/openvpn_tunnels
Previously, the limit was wrongly set to 17
Avoid errors during `fw4 reload` like:
```
/dev/stdin:54:13-30: Error: String exceeds maximum length of 16
iifname { "tuntunnel-uffici", "tuntunnel-sr-ct" } jump input_openvpn comment "!fw4: Handle openvpn IPv4/IPv6 input traffic"
^^^^^^^^^^^^^^^^^^
```
Ref: #1061
> fix(ns-migration): limit tun name to 16 chars

- packages/ns-migration/files/scripts/openvpn_tunnels
Previously, a tunnel could override an existing one during the migration process
If a tunnel with the same name already exists, the migration will create a tunnel named
like `mgr-<md5_partial_hash>`, example: `mgr-9de43`
#1062
> fix(ns-migration): avoid ovpn tunnel collision

- packages/ns-api/Makefile
During an update the /etc/config/templates was renamed to /etc/config/templates-opkg: this will break
expectations of packages which are using the templates for automatic configuration (eg. migration, wireguard)
> fix(ns-api): mark templates file as non-config

- packages/ns-api/Makefile
- packages/ns-api/README.md
- packages/ns-api/files/ns.ssh
- packages/ns-ui/Makefile
Removing `file` call usage from the UI, this will then be blocked in future PR.
Ref:
- https://github.com/NethServer/nethsecurity/issues/1075
> refactor!(ns-api): removed `file` calls for SSH keys

- packages/ns-migration/files/scripts/network
- packages/ns-migration/files/scripts/wan
> fix(migration): handle truncated wan 

- packages/ns-api/files/ns.report
Following [what happens when data is dumped to controller](https://github.com/NethServer/nethsecurity/blob/35346f89fe6a4df19cc7e2b6a628c9bd2695f530/packages/ns-api/files/ns.controller#L172), removed `kernel` keyword from filtering.
Ref:
- https://github.com/NethServer/nethsecurity/issues/1081
> fix(ns-api): removing kernel keyword from banip count

- packages/ns-api/Makefile
- packages/ns-api/files/firewall-apply-default-logging
- packages/ns-api/files/ns.redirects
- packages/python3-nethsec/Makefile
Add script to apply log limit to all existing rules where logging is enabled.
The script will add the limit to:
- forward rules
- redirect rules
- zones
Usage:
```
uci set firewall.ns_defaults.zone_log_limit="10/s"
uci commit firewall
firewall-apply-default-logging
```
You can ignore the following warnings on firewall reload:
```
Section ns_defaults specifies unknown option 'rule_log_limit'
Section ns_defaults specifies unknown option 'zone_log_limit'
Section ns_defaults specifies unknown option 'redirect_log_limit'
```
Requires: NethServer/python3-nethsec#93
Refs:
- NethServer/nethsecurity#1105
- NethServer/nethsecurity-docs#154
> feat(ns-api): add firewall-apply-default-logging

- packages/ns-plug/files/ns-plug.init
When you `unregister` the unit from the controller, the `ns-plug` service is being restarted instead of stopped.
This worked before due to [these checks](https://github.com/NethServer/nethsecurity/blob/091435ffa5687649cfa2eaf1d1a743fff40046b2/packages/ns-plug/files/ns-plug#L23-L36) inside the `ns-plug` script. This however triggers a restart loop using the new procd restart.
Using the procd get config to stop the service before init so that no restart is actually made.
Ref: 
- https://github.com/NethServer/nethsecurity/issues/1084
> fix(ns-plug): soft stop when deregistering the unit

- config/f2fs-tools.conf
Storage and filesystem may develop errors (especially on usb-key): add the f2fsck tool to fix errors (avoids reflashing).
> feat(packages): add f2fsck

- patches/feeds/packages/200-coova-curl-debug.patch
This PR addresses two reliability and compatibility improvements in the
coova-chilli proxy:
- **Refactored debug logging** to honor the runtime `_options.debug` flag
instead of compile-time `_debug_` checks. This ensures debug output is
dynamically controllable during operation, avoiding unnecessary logs when
debugging is disabled.
- **Enforced HTTP/1.1 in curl requests** to resolve protocol errors (e.g.,
`HTTP/2 stream not closed cleanly`) caused by servers incompatible with
HTTP/2. Explicitly setting the version prevents unpredictable failures and
improves compatibility with legacy systems
* https://github.com/NethServer/nethsecurity/issues/1113
> fix(coova-chilli): enforce HTTP/1.1 for curl compatibility

- packages/ns-dpi/files/dpi-config
- packages/python3-nethsec/Makefile
DPI filter lost the ability to filter vlans when de-duplication of analysis and traffic took place in https://github.com/NethServer/nethsecurity/issues/929. This PR aims to restore the functionality.
Requires: https://github.com/NethServer/python3-nethsec/pull/94
Ref:
- https://github.com/NethServer/nethsecurity/issues/1101
> feat(ns-dpi): supporting vlans

- packages/mwan3/Makefile
- packages/mwan3/files/etc/init.d/mwan3
- packages/mwan3/files/etc/uci-defaults/mwan3-addroutertraffic-execution
- packages/mwan3/files/lib/mwan3/mwan3.sh
- packages/mwan3/files/usr/libexec/mwan3routertraffic
- packages/mwan3/files/usr/sbin/mwan3routertraffic
By leveraging /etc/mwan3.user, we can generate ip rules that force traffic to be routed to specific interfaces. This PR reverts 05fbb03d1d1fae30f2fe486dcffde3772c2d76f4 and implements back the functionality.
Ref:
- https://github.com/NethServer/nethsecurity/issues/1126
> fix(mwan3): fix wrong traffic routing with specific metrics

- packages/ns-api/files/ns.threatshield
Regression introduced by ba2892a988e7c5eecbd4ca0d37792f1b51909b1e
Fix error:
```
File "/usr/libexec/rpcd/ns.threatshield", line 196, in edit_blocklist
feeds = list_feeds(has_bl)
^^^^^^^^^^^^^^^^^^
```
NethServer/nethsecurity#1172
> fix(ns-api): banip, fix regression

- packages/ns-api/files/ns.report
Due to the usage just for the monitoring view, adjusted the find-public-ip API of `ns.report` to use device name as a discriminant for IP resolution.
Ref: https://github.com/NethServer/nethsecurity/issues/1175
> refactor(ns-api): refactored api call that returned public ips

- packages/ns-api/files/ns.redirects
Return all protocols from `/etc/protocols`
NethServer/nethsecurity#1069
From manual, the `proto` field supports the following:
> Match incoming traffic using the given protocol. Can be one (or several when using list syntax) of tcp, udp, udplite, icmp, esp, ah, sctp, or all or it can be a numeric value, representing one of these protocols or a different one. A protocol name from /etc/protocols is also allowed. The number 0 is equivalent to all.
See https://openwrt.org/docs/guide-user/firewall/firewall_configuration
> feat(ns-api): redirects, show all supported protocols

- packages/snort3/README.md
- packages/snort3/files/ns-snort-rules
- packages/snort3/files/snort.init
Due to implementation, rules were not generated again if download wasn't needed
https://github.com/NethServer/nethsecurity/issues/1165
> fix(snort3): generating config even without downloading rules

- packages/ns-plug/files/backup-encryption-alert
Avoid unwanted output during cron execution
See #1119
> fix(ns-plug): hide backup-encryption-alert output

- packages/ns-api/files/ns.report
When checking for the public IP of a PPPoE device, the API must search for the real device name
which is like 'pppoe-<interface_name>'.
Before this fix, all PPPoE interfaces did not show the public IP address.
#1148
> fix(ns-api): get public IP for PPPoE

- packages/ns-api/files/ns.ovpnrw
- packages/ns-openvpn/files/openvpn-otp-auth
If the OpenVPN RoadWarrior server is attached to a remote database and the authentication is OTP based, verify also if the user is still present inside the remote LDAP server.
The check is done using a remote LDAP query searching for an entry that matches `<user_att>r=<user_name>`.
Example: `sAMAccountName=jack`
Changes for the UI: https://github.com/NethServer/nethsecurity-ui/pull/548
Issue: #1209
> OpenVPN RW: add remote validation for OTP authentication

- packages/ns-api/files/ns.threatshield
Added APIs for feature linked below
Ref: https://github.com/NethServer/nethsecurity/issues/924
> feat(threatshield): active block list and ip search

- packages/ns-api/files/ns.nat
- packages/python3-nethsec/Makefile
Needs: https://github.com/NethServer/python3-nethsec/pull/99
Closes: https://github.com/NethServer/nethsecurity/issues/1183
> feat(ns-api): added device narrowing for nats

- packages/ns-api/files/ns.redirects
Closes https://github.com/NethServer/nethsecurity/issues/1220
> fix(port forward): allow redirect to firewall

- packages/ns-api/files/ns.ovpnrw
Previously, users deleted from remote user database could not be deleted from OpenVPN configuration due to a user_not_found validation error
Closed #1209
> fix(ns-api): ovpnrw, allow deletion of dangling users

- packages/ns-api/files/ns.ha
- packages/ns-ha/files/ns-ha-config
Changes:
* [`packages/ns-api/files/ns.ha`](diffhunk://#diff-2f5f54847acc6115b8ec5a04723bd54d8adabb9531d13a55035429739fd9ac43R645-R646): Added a step to enable `keepalived` in the `init_local` function to ensure it is active if previously disabled by the reset API.
* [`packages/ns-api/files/ns.ha`](diffhunk://#diff-2f5f54847acc6115b8ec5a04723bd54d8adabb9531d13a55035429739fd9ac43R1036-R1038): Added a check in the `upgrade_remote` function to return an error if the specified image file does not exist, preventing further processing.
* [`packages/ns-ha/files/ns-ha-config`](diffhunk://#diff-14ec4f5b2ddfbdd40330ebb3510b8526c067fefcd004a50d67f21f4a81d4f70aL512-R516): Updated the `ns-ha-config` script to provide detailed error messages by parsing and displaying the error field from the RPC …
> HA: minor fixes

- packages/ns-flashstart/README.md
- packages/ns-flashstart/files/ns-flashstart
Closes: https://github.com/NethServer/nethsecurity/issues/1162
> feat(flashstart): allow setting of logqueries and rebind in generated servers

- packages/ns-api/files/ns.wireguard
Improve readability adding a dash in the rule name and comment
> fix(wireguard): add dash to rule name

- files/etc/config/firewall
- packages/ns-api/files/ns.threatshield
This PR will:
- Set as disabled the synflood management of fw4 on new installations
- Add new APIs for let synflood be managed by banIP
Closes https://github.com/NethServer/nethsecurity/issues/1158
> feat(banip): added dos management

- packages/ns-plug/files/inventory
The ifconfig.co site sometimes returns an HTML page and this info is wrongly sent to my.nethesis.it
New behavior:
- send an HTTP request to ifconfig.co and parse the response, if the remote server returns a valid IP address, return it
- otherwise, try to obtain the same info by executing a DNS query to OpenDNS
- return an empty string if none of the above responses are valid IP addresses
> fix(ns-plug): inventory, better public IP retrival

- files/usr/libexec/login.sh
Use "vt102" for serial console terminal
See https://github.com/openwrt/openwrt/commit/1310e4f1aecef6c2c1b68227216ba7cc04006002 for details.
> chore(base-files): Better TERM for serial console

- packages/ns-api/files/ns.threatshield
The whitelist is now available for all machines with a subscription. So the whitelist download can't be used to check if the machine has a valid entitlement for the blacklist service.
Fixes: #1364
> feat(ns-api): threat shield, whitelist for everyone
